import { Recipe, Chef, Masterclass, Job, Supplier, Episode } from '@/types/index';

export const MOCK_CHEFS: Chef[] = [
  // Original 5 chefs
  {
    id: 'chef-1',
    name: 'Massimo Bottura',
    avatar: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=400&h=400&fit=crop',
    bio: 'Three-Michelin-starred chef and innovator of modern Italian cuisine. Known for transforming traditional dishes with contemporary techniques.',
    cuisine: ['Italian', 'Modern European'],
    accolades: [
      { type: 'michelin', stars: 3, year: 2023, restaurant: 'Osteria Francescana' },
      { type: 'fifty_best', year: 2023 },
    ],
    restaurant: 'Osteria Francescana',
    yearsExperience: 35,
    specialties: ['Modernist Cooking', 'Italian Cuisine', 'Molecular Gastronomy'],
    recipes: [],
    masterclasses: [],
    createdAt: new Date(),
  },
  {
    id: 'chef-2',
    name: 'René Redzepi',
    avatar: 'https://images.unsplash.com/photo-1581299894007-aaa50297cf16?w=400&h=400&fit=crop',
    bio: 'Pioneer of New Nordic Cuisine. Focuses on hyper-local, seasonal ingredients and sustainable practices.',
    cuisine: ['Nordic', 'Scandinavian'],
    accolades: [
      { type: 'michelin', stars: 3, year: 2023, restaurant: 'Noma' },
      { type: 'fifty_best', year: 2023 },
    ],
    restaurant: 'Noma',
    yearsExperience: 30,
    specialties: ['Nordic Cuisine', 'Foraging', 'Sustainability'],
    recipes: [],
    masterclasses: [],
    createdAt: new Date(),
  },
  {
    id: 'chef-3',
    name: 'Gaggan Anand',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=400&fit=crop',
    bio: 'Visionary chef redefining modern Indian cuisine with progressive techniques and emotional storytelling through food.',
    cuisine: ['Indian', 'Contemporary'],
    accolades: [
      { type: 'michelin', stars: 2, year: 2023, restaurant: 'Gaggan' },
      { type: 'fifty_best', year: 2023 },
    ],
    restaurant: 'Gaggan',
    yearsExperience: 28,
    specialties: ['Contemporary Indian', 'Molecular Gastronomy', 'Culinary Art'],
    recipes: [],
    masterclasses: [],
    createdAt: new Date(),
  },
  {
    id: 'chef-4',
    name: 'Thomas Keller',
    avatar: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&h=400&fit=crop',
    bio: 'Master of French classical technique. Renowned for precise, elegant cuisine with impeccable execution.',
    cuisine: ['French', 'American Contemporary'],
    accolades: [
      { type: 'michelin', stars: 3, year: 2023, restaurant: 'The French Laundry' },
      { type: 'fifty_best', year: 2023 },
    ],
    restaurant: 'The French Laundry',
    yearsExperience: 40,
    specialties: ['French Cuisine', 'Classical Technique', 'Fine Dining'],
    recipes: [],
    masterclasses: [],
    createdAt: new Date(),
  },
  {
    id: 'chef-5',
    name: 'Clare Smyth',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
    bio: 'Chef-patron of the acclaimed restaurant Core. Specializes in innovative British cuisine with Japanese influences.',
    cuisine: ['British', 'Japanese Fusion'],
    accolades: [
      { type: 'michelin', stars: 2, year: 2023, restaurant: 'Core by Clare Smyth' },
    ],
    restaurant: 'Core by Clare Smyth',
    yearsExperience: 25,
    specialties: ['British Cuisine', 'Japanese Techniques', 'Innovation'],
    recipes: [],
    masterclasses: [],
    createdAt: new Date(),
  },
  // New 5 chefs
  {
    id: 'chef-6',
    name: 'Alain Ducasse',
    avatar: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=400&h=400&fit=crop',
    bio: 'Legendary French chef with restaurants across the globe. Pioneer in sustainable gastronomy and a master of technique.',
    cuisine: ['French', 'Mediterranean', 'Contemporary'],
    accolades: [
      { type: 'michelin', stars: 3, year: 2023, restaurant: 'Le Jules Verne' },
      { type: 'fifty_best', year: 2023 },
    ],
    restaurant: 'Le Jules Verne',
    yearsExperience: 45,
    specialties: ['French Classical', 'Fine Dining', 'Sustainability'],
    recipes: [],
    masterclasses: [],
    createdAt: new Date(),
  },
  {
    id: 'chef-7',
    name: 'Heston Blumenthal',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    bio: 'British chef celebrated for pioneering molecular gastronomy. Combines science, art, and psychology in culinary innovation.',
    cuisine: ['British', 'Modernist', 'Experimental'],
    accolades: [
      { type: 'michelin', stars: 3, year: 2023, restaurant: 'The Fat Duck' },
      { type: 'fifty_best', year: 2023 },
    ],
    restaurant: 'The Fat Duck',
    yearsExperience: 32,
    specialties: ['Molecular Gastronomy', 'Culinary Innovation', 'Science in Cooking'],
    recipes: [],
    masterclasses: [],
    createdAt: new Date(),
  },
  {
    id: 'chef-8',
    name: 'Dominique Crenn',
    avatar: 'https://images.unsplash.com/photo-1504674900152-b8b80e7b6c5d?w=400&h=400&fit=crop',
    bio: 'First female chef in France to earn three Michelin stars. Renowned for poetic plating and contemporary French cuisine.',
    cuisine: ['French', 'Contemporary', 'Modern European'],
    accolades: [
      { type: 'michelin', stars: 3, year: 2023, restaurant: 'Atelier Crenn' },
      { type: 'fifty_best', year: 2023 },
    ],
    restaurant: 'Atelier Crenn',
    yearsExperience: 34,
    specialties: ['French Contemporary', 'Poetic Plating', 'Culinary Art'],
    recipes: [],
    masterclasses: [],
    createdAt: new Date(),
  },
  {
    id: 'chef-9',
    name: 'Yoshihiro Narisawa',
    avatar: 'https://images.unsplash.com/photo-1494897692104-481c6b1dc239?w=400&h=400&fit=crop',
    bio: 'Japanese chef pioneering innovative Japanese cuisine. Focused on sustainability and respect for ingredients.',
    cuisine: ['Japanese', 'Contemporary Japanese', 'Modern'],
    accolades: [
      { type: 'michelin', stars: 3, year: 2023, restaurant: 'Narisawa' },
      { type: 'fifty_best', year: 2023 },
    ],
    restaurant: 'Narisawa',
    yearsExperience: 33,
    specialties: ['Contemporary Japanese', 'Sustainability', 'Innovation'],
    recipes: [],
    masterclasses: [],
    createdAt: new Date(),
  },
  {
    id: 'chef-10',
    name: 'Ana Roš',
    avatar: 'https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=400&h=400&fit=crop',
    bio: 'Slovenian chef celebrated for seasonal, local, and foraged ingredients. Runner-up World Best Female Chef.',
    cuisine: ['Slovenian', 'Nordic', 'Contemporary'],
    accolades: [
      { type: 'michelin', stars: 2, year: 2023, restaurant: 'Hiša Franko' },
      { type: 'fifty_best', year: 2023 },
    ],
    restaurant: 'Hiša Franko',
    yearsExperience: 29,
    specialties: ['Foraging', 'Sustainability', 'Alpine Cuisine'],
    recipes: [],
    masterclasses: [],
    createdAt: new Date(),
  },
];

export const MOCK_RECIPES: Recipe[] = [
  // Original 5 recipes
  {
    id: 'recipe-1',
    title: 'Risotto ai Funghi Porcini',
    chef: MOCK_CHEFS[0],
    restaurant: 'Osteria Francescana',
    description: 'Creamy arborio rice with wild porcini mushrooms, perfectly balanced with truffle oil and Parmigiano-Reggiano.',
    cuisines: [
      { id: 'italian', name: 'Italian', parent: 'european' },
      { id: 'italian_northern', name: 'Northern Italian', parent: 'italian' },
    ],
    techniques: [
      { id: 'simmering', name: 'Simmering', category: 'wet_heat', description: 'Cooking in gently bubbling liquid' },
      { id: 'pan_frying', name: 'Pan-Frying', category: 'dry_heat', description: 'Cooking in a shallow pan with oil' },
    ],
    station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
    difficulty: 'intermediate',
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    yield: 'Serves 4 as main course',
    ingredients: [
      { id: 'i1', name: 'Arborio Rice', weight: 300, unit: 'g', allergens: [], group: 'grain', sustainability: 'standard' },
      { id: 'i2', name: 'Porcini Mushrooms (dried)', weight: 20, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'seasonal' },
      { id: 'i3', name: 'White Wine', weight: 100, unit: 'ml', allergens: [], group: 'other', sustainability: 'standard' },
      { id: 'i4', name: 'Vegetable Stock', weight: 1000, unit: 'ml', allergens: [], group: 'other', sustainability: 'standard' },
      { id: 'i5', name: 'Butter', weight: 50, unit: 'g', allergens: ['milk'], group: 'dairy', sustainability: 'standard' },
      { id: 'i6', name: 'Parmigiano-Reggiano', weight: 80, unit: 'g', allergens: ['milk'], group: 'dairy', sustainability: 'standard' },
      { id: 'i7', name: 'Truffle Oil', weight: 5, unit: 'ml', allergens: [], group: 'oil', sustainability: 'standard' },
      { id: 'i8', name: 'Salt', weight: 5, unit: 'g', allergens: [], group: 'seasoning', sustainability: 'standard' },
      { id: 'i9', name: 'Black Pepper', weight: 2, unit: 'g', allergens: [], group: 'seasoning', sustainability: 'standard' },
    ],
    steps: [
      {
        id: 's1',
        order: 1,
        instruction: 'Rehydrate porcini mushrooms in hot water for 15 minutes. Reserve the soaking liquid.',
        techniques: [],
        station: null,
        duration: 15,
      },
      {
        id: 's2',
        order: 2,
        instruction: 'Heat vegetable stock with mushroom soaking liquid in a separate pot and keep warm.',
        techniques: [],
        station: null,
        duration: 5,
      },
      {
        id: 's3',
        order: 3,
        instruction: 'Heat olive oil in a large pan, add shallots and sauté until softened.',
        techniques: ['pan_frying'],
        station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
        duration: 3,
      },
      {
        id: 's4',
        order: 4,
        instruction: 'Add Arborio rice and toast for 2 minutes, stirring constantly.',
        techniques: ['pan_frying'],
        station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
        duration: 2,
      },
      {
        id: 's5',
        order: 5,
        instruction: 'Deglaze with white wine, stirring until absorbed.',
        techniques: [],
        station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
        duration: 2,
      },
      {
        id: 's6',
        order: 6,
        instruction: 'Add warm stock one ladle at a time, stirring frequently until rice is creamy and al dente.',
        techniques: ['simmering'],
        station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
        duration: 18,
      },
      {
        id: 's7',
        order: 7,
        instruction: 'Finish with butter, Parmigiano-Reggiano, and truffle oil. Season with salt and pepper.',
        techniques: [],
        station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
        duration: 2,
      },
    ],
    allergens: [
      { id: 'milk', name: 'Milk (including lactose)', code: 'milk' },
    ],
    foodCostPercent: 28,
    image: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800&h=600&fit=crop',
    menuContext: ['a_la_carte', 'tasting_menu'],
    sustainability: {
      lowCarbon: true,
      seasonal: true,
      zeroWaste: false,
      score: 72,
    },
    rating: 4.8,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'recipe-2',
    title: 'Smørrebrød with Cured Fish',
    chef: MOCK_CHEFS[1],
    restaurant: 'Noma',
    description: 'Traditional Danish open-faced sandwich featuring house-cured Nordic fish on dense rye bread with seasonal vegetables.',
    cuisines: [
      { id: 'nordic', name: 'Nordic', parent: 'european' },
    ],
    techniques: [
      { id: 'curing', name: 'Curing', category: 'preservation', description: 'Preserving with salt and spices' },
    ],
    station: { id: 'garde_manger', name: 'Garde Manger', description: 'Cold station' },
    difficulty: 'intermediate',
    prepTime: 30,
    cookTime: 0,
    servings: 2,
    ingredients: [
      { id: 'i10', name: 'Rye Bread', weight: 200, unit: 'g', allergens: ['cereals'], group: 'grain', sustainability: 'local' },
      { id: 'i11', name: 'Fresh White Fish', weight: 300, unit: 'g', allergens: ['fish'], group: 'protein', sustainability: 'seasonal' },
      { id: 'i12', name: 'Sea Salt', weight: 10, unit: 'g', allergens: [], group: 'seasoning', sustainability: 'standard' },
      { id: 'i13', name: 'Dill', weight: 10, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'seasonal' },
      { id: 'i14', name: 'Beetroot', weight: 100, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'seasonal' },
      { id: 'i15', name: 'Crème Fraîche', weight: 50, unit: 'g', allergens: ['milk'], group: 'dairy', sustainability: 'standard' },
    ],
    steps: [
      {
        id: 's8',
        order: 1,
        instruction: 'Cure white fish with sea salt and dill for 24 hours.',
        techniques: ['curing'],
        station: { id: 'garde_manger', name: 'Garde Manger', description: 'Cold station' },
        duration: 1440,
      },
      {
        id: 's9',
        order: 2,
        instruction: 'Roast beetroots until tender, then cut into thin slices.',
        techniques: [],
        station: null,
        duration: 45,
      },
      {
        id: 's10',
        order: 3,
        instruction: 'Slice rye bread and toast lightly.',
        techniques: ['roasting'],
        station: null,
        duration: 3,
      },
      {
        id: 's11',
        order: 4,
        instruction: 'Assemble: spread crème fraîche on bread, top with cured fish, beetroot, and fresh dill.',
        techniques: [],
        station: { id: 'garde_manger', name: 'Garde Manger', description: 'Cold station' },
        duration: 5,
      },
    ],
    allergens: [
      { id: 'cereals', name: 'Cereals containing gluten', code: 'gluten' },
      { id: 'fish', name: 'Fish', code: 'fish' },
      { id: 'milk', name: 'Milk (including lactose)', code: 'milk' },
    ],
    foodCostPercent: 35,
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&h=600&fit=crop',
    menuContext: ['a_la_carte', 'brunch'],
    sustainability: {
      lowCarbon: true,
      seasonal: true,
      zeroWaste: true,
      score: 88,
    },
    rating: 4.9,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'recipe-3',
    title: 'Saffron Risotto with Sea Urchin',
    chef: MOCK_CHEFS[2],
    restaurant: 'Gaggan',
    description: 'Elegant North Indian-influenced risotto with delicate saffron, finished with luxurious sea urchin roe.',
    cuisines: [
      { id: 'indian', name: 'Indian', parent: 'asian' },
      { id: 'indian_contemporary', name: 'Contemporary', parent: 'indian' },
    ],
    techniques: [
      { id: 'simmering', name: 'Simmering', category: 'wet_heat', description: 'Cooking in gently bubbling liquid' },
      { id: 'tempering', name: 'Tempering', category: 'pastry', description: 'Controlling chocolate crystallization' },
    ],
    station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
    difficulty: 'advanced',
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    ingredients: [
      { id: 'i16', name: 'Arborio Rice', weight: 280, unit: 'g', allergens: [], group: 'grain', sustainability: 'standard' },
      { id: 'i17', name: 'Saffron', weight: 0.5, unit: 'g', allergens: [], group: 'seasoning', sustainability: 'standard' },
      { id: 'i18', name: 'Sea Urchin Roe', weight: 80, unit: 'g', allergens: ['mollusks'], group: 'protein', sustainability: 'seasonal' },
      { id: 'i19', name: 'White Wine', weight: 100, unit: 'ml', allergens: [], group: 'other', sustainability: 'standard' },
      { id: 'i20', name: 'Fish Stock', weight: 1000, unit: 'ml', allergens: ['fish'], group: 'other', sustainability: 'standard' },
      { id: 'i21', name: 'Butter', weight: 60, unit: 'g', allergens: ['milk'], group: 'dairy', sustainability: 'standard' },
      { id: 'i22', name: 'Parmigiano-Reggiano', weight: 70, unit: 'g', allergens: ['milk'], group: 'dairy', sustainability: 'standard' },
    ],
    steps: [
      {
        id: 's12',
        order: 1,
        instruction: 'Steep saffron in warm fish stock for 10 minutes.',
        techniques: [],
        station: null,
        duration: 10,
      },
      {
        id: 's13',
        order: 2,
        instruction: 'Toast rice briefly in ghee with shallots.',
        techniques: ['pan_frying'],
        station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
        duration: 3,
      },
      {
        id: 's14',
        order: 3,
        instruction: 'Deglaze with white wine and allow to evaporate.',
        techniques: [],
        station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
        duration: 2,
      },
      {
        id: 's15',
        order: 4,
        instruction: 'Gradually add saffron-infused stock, stirring frequently until rice reaches perfect creaminess.',
        techniques: ['simmering'],
        station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
        duration: 18,
      },
      {
        id: 's16',
        order: 5,
        instruction: 'Finish with cold butter and Parmigiano, then top with sea urchin roe just before serving.',
        techniques: [],
        station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
        duration: 2,
      },
    ],
    allergens: [
      { id: 'mollusks', name: 'Mollusks', code: 'mollusks' },
      { id: 'fish', name: 'Fish', code: 'fish' },
      { id: 'milk', name: 'Milk (including lactose)', code: 'milk' },
    ],
    foodCostPercent: 42,
    image: 'https://images.unsplash.com/photo-1494897692104-481c6b1dc239?w=800&h=600&fit=crop',
    menuContext: ['tasting_menu'],
    sustainability: {
      lowCarbon: false,
      seasonal: true,
      zeroWaste: false,
      score: 65,
    },
    rating: 4.7,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'recipe-4',
    title: 'Roasted Duck Breast with Cherry Gastrique',
    chef: MOCK_CHEFS[3],
    restaurant: 'The French Laundry',
    description: 'Perfect medium-rare duck breast with crispy skin, accompanied by a glossy cherry gastrique and seasonal vegetables.',
    cuisines: [
      { id: 'french', name: 'French', parent: 'european' },
      { id: 'french_classical', name: 'Classical', parent: 'french' },
    ],
    techniques: [
      { id: 'roasting', name: 'Roasting', category: 'dry_heat', description: 'Cooking with dry heat in an oven' },
      { id: 'searing', name: 'Searing', category: 'dry_heat', description: 'High-heat cooking to create crust' },
    ],
    station: { id: 'rotisseur', name: 'Rôtisseur', description: 'Roast station' },
    difficulty: 'advanced',
    prepTime: 20,
    cookTime: 30,
    servings: 4,
    ingredients: [
      { id: 'i23', name: 'Duck Breast', weight: 800, unit: 'g', allergens: [], group: 'protein', sustainability: 'standard' },
      { id: 'i24', name: 'Fresh Cherries', weight: 300, unit: 'g', allergens: [], group: 'fruit', sustainability: 'seasonal' },
      { id: 'i25', name: 'Red Wine Vinegar', weight: 50, unit: 'ml', allergens: [], group: 'other', sustainability: 'standard' },
      { id: 'i26', name: 'Sugar', weight: 50, unit: 'g', allergens: [], group: 'seasoning', sustainability: 'standard' },
      { id: 'i27', name: 'Duck Stock', weight: 200, unit: 'ml', allergens: [], group: 'other', sustainability: 'standard' },
      { id: 'i28', name: 'Thyme', weight: 5, unit: 'g', allergens: [], group: 'seasoning', sustainability: 'seasonal' },
      { id: 'i29', name: 'Sea Salt', weight: 5, unit: 'g', allergens: [], group: 'seasoning', sustainability: 'standard' },
    ],
    steps: [
      {
        id: 's17',
        order: 1,
        instruction: 'Score duck skin crosshatch pattern without cutting into flesh.',
        techniques: [],
        station: { id: 'rotisseur', name: 'Rôtisseur', description: 'Roast station' },
        duration: 5,
      },
      {
        id: 's18',
        order: 2,
        instruction: 'Season duck breasts with salt and pepper.',
        techniques: [],
        station: { id: 'rotisseur', name: 'Rôtisseur', description: 'Roast station' },
        duration: 2,
      },
      {
        id: 's19',
        order: 3,
        instruction: 'Sear skin-side down in cold pan, gradually increasing heat to render fat until skin is golden and crispy.',
        techniques: ['searing'],
        station: { id: 'rotisseur', name: 'Rôtisseur', description: 'Roast station' },
        duration: 10,
      },
      {
        id: 's20',
        order: 4,
        instruction: 'Flip and sear meat side briefly, then roast at 60°C until medium-rare.',
        techniques: ['roasting', 'searing'],
        station: { id: 'rotisseur', name: 'Rôtisseur', description: 'Roast station' },
        duration: 12,
      },
      {
        id: 's21',
        order: 5,
        instruction: 'Rest duck for 8 minutes while preparing gastrique.',
        techniques: [],
        station: null,
        duration: 8,
      },
      {
        id: 's22',
        order: 6,
        instruction: 'For gastrique: combine sugar and vinegar, caramelize sugar, add cherries and stock, reduce until glossy.',
        techniques: [],
        station: { id: 'saucier', name: 'Saucier', description: 'Sauce station' },
        duration: 8,
      },
    ],
    allergens: [],
    foodCostPercent: 38,
    image: 'https://images.unsplash.com/photo-1432139509613-5c4255a1d127?w=800&h=600&fit=crop',
    menuContext: ['a_la_carte', 'tasting_menu'],
    sustainability: {
      lowCarbon: false,
      seasonal: true,
      zeroWaste: false,
      score: 58,
    },
    rating: 4.9,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'recipe-5',
    title: 'Oyster with Champagne Foam',
    chef: MOCK_CHEFS[4],
    restaurant: 'Core by Clare Smyth',
    description: 'Fresh British oyster topped with delicate champagne foam and caviar, a celebration of minimalism and precision.',
    cuisines: [
      { id: 'british', name: 'British', parent: 'european' },
    ],
    techniques: [
      { id: 'foaming', name: 'Foaming', category: 'modernist', description: 'Creating foams and airs' },
    ],
    station: { id: 'garde_manger', name: 'Garde Manger', description: 'Cold station' },
    difficulty: 'advanced',
    prepTime: 15,
    cookTime: 5,
    servings: 6,
    ingredients: [
      { id: 'i30', name: 'Fresh Oysters', weight: 150, unit: 'g', allergens: ['mollusks'], group: 'protein', sustainability: 'seasonal' },
      { id: 'i31', name: 'Champagne', weight: 100, unit: 'ml', allergens: [], group: 'other', sustainability: 'standard' },
      { id: 'i32', name: 'Lecithin', weight: 2, unit: 'g', allergens: ['soybeans'], group: 'other', sustainability: 'standard' },
      { id: 'i33', name: 'Caviar', weight: 20, unit: 'g', allergens: ['fish'], group: 'protein', sustainability: 'standard' },
      { id: 'i34', name: 'Salt', weight: 2, unit: 'g', allergens: [], group: 'seasoning', sustainability: 'standard' },
      { id: 'i35', name: 'Lemon', weight: 30, unit: 'g', allergens: [], group: 'fruit', sustainability: 'seasonal' },
    ],
    steps: [
      {
        id: 's23',
        order: 1,
        instruction: 'Shuck oysters carefully, keeping in their shells and ice-cold.',
        techniques: [],
        station: { id: 'garde_manger', name: 'Garde Manger', description: 'Cold station' },
        duration: 10,
      },
      {
        id: 's24',
        order: 2,
        instruction: 'Combine champagne with soy lecithin using an immersion blender to create stable foam.',
        techniques: ['foaming'],
        station: { id: 'garde_manger', name: 'Garde Manger', description: 'Cold station' },
        duration: 5,
      },
      {
        id: 's25',
        order: 3,
        instruction: 'Top each oyster with champagne foam and a pearl of caviar.',
        techniques: ['foaming'],
        station: { id: 'garde_manger', name: 'Garde Manger', description: 'Cold station' },
        duration: 2,
      },
      {
        id: 's26',
        order: 4,
        instruction: 'Garnish with microgreens and a squeeze of fresh lemon juice.',
        techniques: [],
        station: { id: 'garde_manger', name: 'Garde Manger', description: 'Cold station' },
        duration: 1,
      },
    ],
    allergens: [
      { id: 'mollusks', name: 'Mollusks', code: 'mollusks' },
      { id: 'fish', name: 'Fish', code: 'fish' },
      { id: 'soybeans', name: 'Soybeans', code: 'soybeans' },
    ],
    foodCostPercent: 45,
    image: 'https://images.unsplash.com/photo-1514516345957-556ca7d90a29?w=800&h=600&fit=crop',
    menuContext: ['tasting_menu'],
    sustainability: {
      lowCarbon: true,
      seasonal: true,
      zeroWaste: true,
      score: 82,
    },
    rating: 4.8,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // New 10 recipes
  {
    id: 'recipe-6',
    title: 'Beef Tartare with Quail Egg and Caper',
    chef: MOCK_CHEFS[5],
    restaurant: 'Le Jules Verne',
    description: 'Premium beef tartare with ultra-fresh ingredients, quail egg yolk, and delicate capers on crisp toast.',
    cuisines: [
      { id: 'french', name: 'French', parent: 'european' },
      { id: 'french_classical', name: 'Classical', parent: 'french' },
    ],
    techniques: [
      { id: 'knife_work', name: 'Knife Work', category: 'dry_heat', description: 'Fine chopping and preparation' },
    ],
    station: { id: 'garde_manger', name: 'Garde Manger', description: 'Cold station' },
    difficulty: 'advanced',
    prepTime: 20,
    cookTime: 0,
    servings: 4,
    ingredients: [
      { id: 'i36', name: 'Prime Beef', weight: 400, unit: 'g', allergens: [], group: 'protein', sustainability: 'standard' },
      { id: 'i37', name: 'Quail Eggs', weight: 60, unit: 'g', allergens: ['eggs'], group: 'protein', sustainability: 'standard' },
      { id: 'i38', name: 'Capers', weight: 15, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'standard' },
      { id: 'i39', name: 'Shallots', weight: 30, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'seasonal' },
      { id: 'i40', name: 'Dijon Mustard', weight: 10, unit: 'g', allergens: ['mustard'], group: 'seasoning', sustainability: 'standard' },
      { id: 'i41', name: 'Toast Points', weight: 80, unit: 'g', allergens: ['cereals'], group: 'grain', sustainability: 'standard' },
      { id: 'i42', name: 'Cornichons', weight: 30, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'standard' },
      { id: 'i43', name: 'Olive Oil', weight: 20, unit: 'ml', allergens: [], group: 'oil', sustainability: 'local' },
    ],
    steps: [
      {
        id: 's27',
        order: 1,
        instruction: 'Use only the highest quality prime beef, finely hand-diced into perfect cubes.',
        techniques: ['knife_work'],
        station: { id: 'garde_manger', name: 'Garde Manger', description: 'Cold station' },
        duration: 10,
      },
      {
        id: 's28',
        order: 2,
        instruction: 'Finely mince shallots and capers, add to beef with mustard and olive oil.',
        techniques: ['knife_work'],
        station: { id: 'garde_manger', name: 'Garde Manger', description: 'Cold station' },
        duration: 5,
      },
      {
        id: 's29',
        order: 3,
        instruction: 'Season with fleur de sel and freshly cracked pepper.',
        techniques: [],
        station: { id: 'garde_manger', name: 'Garde Manger', description: 'Cold station' },
        duration: 2,
      },
      {
        id: 's30',
        order: 4,
        instruction: 'Plate tartare and top with quail egg yolk. Serve with toast points and cornichons.',
        techniques: [],
        station: { id: 'garde_manger', name: 'Garde Manger', description: 'Cold station' },
        duration: 3,
      },
    ],
    allergens: [
      { id: 'eggs', name: 'Eggs', code: 'eggs' },
      { id: 'mustard', name: 'Mustard', code: 'mustard' },
      { id: 'cereals', name: 'Cereals containing gluten', code: 'gluten' },
    ],
    foodCostPercent: 55,
    image: 'https://images.unsplash.com/photo-1514516345957-556ca7d90a29?w=800&h=600&fit=crop',
    menuContext: ['a_la_carte', 'tasting_menu'],
    sustainability: {
      lowCarbon: false,
      seasonal: false,
      zeroWaste: false,
      score: 42,
    },
    rating: 4.7,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'recipe-7',
    title: 'Grand Marnier Soufflé',
    chef: MOCK_CHEFS[6],
    restaurant: 'The Fat Duck',
    description: 'Impossibly light Grand Marnier soufflé with hints of bitter chocolate and orange zest, a timeless classic.',
    cuisines: [
      { id: 'french', name: 'French', parent: 'european' },
      { id: 'pastry', name: 'Pastry', parent: 'french' },
    ],
    techniques: [
      { id: 'tempering', name: 'Tempering', category: 'pastry', description: 'Controlling chocolate crystallization' },
      { id: 'whisking', name: 'Whisking', category: 'pastry', description: 'Aerating egg whites' },
    ],
    station: { id: 'patissier', name: 'Pâtissier', description: 'Pastry station' },
    difficulty: 'advanced',
    prepTime: 20,
    cookTime: 18,
    servings: 4,
    ingredients: [
      { id: 'i44', name: 'Egg Whites', weight: 240, unit: 'g', allergens: ['eggs'], group: 'protein', sustainability: 'standard' },
      { id: 'i45', name: 'Grand Marnier', weight: 60, unit: 'ml', allergens: [], group: 'other', sustainability: 'standard' },
      { id: 'i46', name: 'Dark Chocolate', weight: 100, unit: 'g', allergens: ['soy'], group: 'other', sustainability: 'standard' },
      { id: 'i47', name: 'Butter', weight: 40, unit: 'g', allergens: ['milk'], group: 'dairy', sustainability: 'standard' },
      { id: 'i48', name: 'Sugar', weight: 80, unit: 'g', allergens: [], group: 'seasoning', sustainability: 'standard' },
      { id: 'i49', name: 'Orange Zest', weight: 5, unit: 'g', allergens: [], group: 'fruit', sustainability: 'seasonal' },
      { id: 'i50', name: 'Vanilla Extract', weight: 5, unit: 'ml', allergens: [], group: 'seasoning', sustainability: 'standard' },
    ],
    steps: [
      {
        id: 's31',
        order: 1,
        instruction: 'Melt chocolate with butter and Grand Marnier, fold in orange zest.',
        techniques: ['tempering'],
        station: { id: 'patissier', name: 'Pâtissier', description: 'Pastry station' },
        duration: 5,
      },
      {
        id: 's32',
        order: 2,
        instruction: 'Whisk egg whites with sugar until stiff peaks form.',
        techniques: ['whisking'],
        station: { id: 'patissier', name: 'Pâtissier', description: 'Pastry station' },
        duration: 8,
      },
      {
        id: 's33',
        order: 3,
        instruction: 'Fold chocolate mixture into egg whites in two additions.',
        techniques: [],
        station: { id: 'patissier', name: 'Pâtissier', description: 'Pastry station' },
        duration: 3,
      },
      {
        id: 's34',
        order: 4,
        instruction: 'Divide into ramekins and bake at 190°C for 16-18 minutes until risen and centers are just set.',
        techniques: [],
        station: { id: 'patissier', name: 'Pâtissier', description: 'Pastry station' },
        duration: 18,
      },
    ],
    allergens: [
      { id: 'eggs', name: 'Eggs', code: 'eggs' },
      { id: 'milk', name: 'Milk (including lactose)', code: 'milk' },
      { id: 'soy', name: 'Soy', code: 'soy' },
    ],
    foodCostPercent: 18,
    image: 'https://images.unsplash.com/photo-1488477304112-4944851de03d?w=800&h=600&fit=crop',
    menuContext: ['tasting_menu'],
    sustainability: {
      lowCarbon: true,
      seasonal: true,
      zeroWaste: false,
      score: 68,
    },
    rating: 4.9,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'recipe-8',
    title: 'Beef Wellington with Mushroom Duxelles',
    chef: MOCK_CHEFS[7],
    restaurant: 'Atelier Crenn',
    description: 'Tender beef tenderloin wrapped in pastry with luxurious mushroom duxelles, a modern interpretation of a classic.',
    cuisines: [
      { id: 'french', name: 'French', parent: 'european' },
      { id: 'french_contemporary', name: 'Contemporary French', parent: 'french' },
    ],
    techniques: [
      { id: 'searing', name: 'Searing', category: 'dry_heat', description: 'High-heat cooking to create crust' },
      { id: 'roasting', name: 'Roasting', category: 'dry_heat', description: 'Cooking with dry heat in an oven' },
    ],
    station: { id: 'rotisseur', name: 'Rôtisseur', description: 'Roast station' },
    difficulty: 'expert',
    prepTime: 45,
    cookTime: 40,
    servings: 6,
    ingredients: [
      { id: 'i51', name: 'Beef Tenderloin', weight: 1200, unit: 'g', allergens: [], group: 'protein', sustainability: 'standard' },
      { id: 'i52', name: 'Cremini Mushrooms', weight: 400, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'seasonal' },
      { id: 'i53', name: 'Puff Pastry', weight: 400, unit: 'g', allergens: ['cereals', 'milk'], group: 'grain', sustainability: 'standard' },
      { id: 'i54', name: 'Shallots', weight: 50, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'seasonal' },
      { id: 'i55', name: 'Thyme', weight: 5, unit: 'g', allergens: [], group: 'seasoning', sustainability: 'seasonal' },
      { id: 'i56', name: 'Dijon Mustard', weight: 30, unit: 'g', allergens: ['mustard'], group: 'seasoning', sustainability: 'standard' },
      { id: 'i57', name: 'Egg Yolk', weight: 20, unit: 'g', allergens: ['eggs'], group: 'protein', sustainability: 'standard' },
      { id: 'i58', name: 'Butter', weight: 60, unit: 'g', allergens: ['milk'], group: 'dairy', sustainability: 'standard' },
    ],
    steps: [
      {
        id: 's35',
        order: 1,
        instruction: 'Sear beef tenderloin on all sides until golden, then cool.',
        techniques: ['searing'],
        station: { id: 'rotisseur', name: 'Rôtisseur', description: 'Roast station' },
        duration: 8,
      },
      {
        id: 's36',
        order: 2,
        instruction: 'Finely chop mushrooms and shallots, cook until dry, add thyme and cool.',
        techniques: [],
        station: null,
        duration: 15,
      },
      {
        id: 's37',
        order: 3,
        instruction: 'Brush beef with mustard, coat with mushroom duxelles.',
        techniques: [],
        station: { id: 'rotisseur', name: 'Rôtisseur', description: 'Roast station' },
        duration: 5,
      },
      {
        id: 's38',
        order: 4,
        instruction: 'Wrap beef tightly in puff pastry, brush with egg wash.',
        techniques: [],
        station: { id: 'rotisseur', name: 'Rôtisseur', description: 'Roast station' },
        duration: 8,
      },
      {
        id: 's39',
        order: 5,
        instruction: 'Roast at 200°C for 25-30 minutes until pastry is golden and beef is medium-rare.',
        techniques: ['roasting'],
        station: { id: 'rotisseur', name: 'Rôtisseur', description: 'Roast station' },
        duration: 28,
      },
      {
        id: 's40',
        order: 6,
        instruction: 'Rest for 8 minutes before slicing.',
        techniques: [],
        station: null,
        duration: 8,
      },
    ],
    allergens: [
      { id: 'cereals', name: 'Cereals containing gluten', code: 'gluten' },
      { id: 'milk', name: 'Milk (including lactose)', code: 'milk' },
      { id: 'mustard', name: 'Mustard', code: 'mustard' },
      { id: 'eggs', name: 'Eggs', code: 'eggs' },
    ],
    foodCostPercent: 48,
    image: 'https://images.unsplash.com/photo-1432139509613-5c4255a1d127?w=800&h=600&fit=crop',
    menuContext: ['tasting_menu', 'a_la_carte'],
    sustainability: {
      lowCarbon: false,
      seasonal: true,
      zeroWaste: false,
      score: 52,
    },
    rating: 4.8,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'recipe-9',
    title: 'Tonkotsu Ramen with 24-Hour Pork Bone Broth',
    chef: MOCK_CHEFS[8],
    restaurant: 'Narisawa',
    description: 'Rich, creamy pork bone broth simmered for 24 hours, served with tender chashu and silky noodles.',
    cuisines: [
      { id: 'japanese', name: 'Japanese', parent: 'asian' },
      { id: 'japanese_contemporary', name: 'Contemporary', parent: 'japanese' },
    ],
    techniques: [
      { id: 'simmering', name: 'Simmering', category: 'wet_heat', description: 'Cooking in gently bubbling liquid' },
      { id: 'braising', name: 'Braising', category: 'wet_heat', description: 'Cooking covered in liquid' },
    ],
    station: { id: 'saucier', name: 'Saucier', description: 'Sauce station' },
    difficulty: 'advanced',
    prepTime: 30,
    cookTime: 1440,
    servings: 4,
    ingredients: [
      { id: 'i59', name: 'Pork Bones', weight: 2000, unit: 'g', allergens: [], group: 'protein', sustainability: 'standard' },
      { id: 'i60', name: 'Pork Belly', weight: 600, unit: 'g', allergens: [], group: 'protein', sustainability: 'standard' },
      { id: 'i61', name: 'Kombu', weight: 30, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'seasonal' },
      { id: 'i62', name: 'Fresh Ramen Noodles', weight: 400, unit: 'g', allergens: ['cereals', 'eggs'], group: 'grain', sustainability: 'standard' },
      { id: 'i63', name: 'Soft-boiled Eggs', weight: 120, unit: 'g', allergens: ['eggs'], group: 'protein', sustainability: 'standard' },
      { id: 'i64', name: 'Menma', weight: 80, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'standard' },
      { id: 'i65', name: 'Nori', weight: 5, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'standard' },
      { id: 'i66', name: 'Scallions', weight: 30, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'seasonal' },
    ],
    steps: [
      {
        id: 's41',
        order: 1,
        instruction: 'Blanch pork bones, then roast at 200°C for 30 minutes until golden.',
        techniques: [],
        station: null,
        duration: 40,
      },
      {
        id: 's42',
        order: 2,
        instruction: 'Place roasted bones in pot with water and kombu, simmer for 24 hours on low heat.',
        techniques: ['simmering'],
        station: { id: 'saucier', name: 'Saucier', description: 'Sauce station' },
        duration: 1440,
      },
      {
        id: 's43',
        order: 3,
        instruction: 'Braise pork belly at 150°C for 3 hours until tender, slice before serving.',
        techniques: ['braising'],
        station: { id: 'rotisseur', name: 'Rôtisseur', description: 'Roast station' },
        duration: 180,
      },
      {
        id: 's44',
        order: 4,
        instruction: 'Cook fresh ramen noodles, assemble in bowl with broth, chashu, egg, and toppings.',
        techniques: [],
        station: { id: 'saucier', name: 'Saucier', description: 'Sauce station' },
        duration: 5,
      },
    ],
    allergens: [
      { id: 'cereals', name: 'Cereals containing gluten', code: 'gluten' },
      { id: 'eggs', name: 'Eggs', code: 'eggs' },
    ],
    foodCostPercent: 22,
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&h=600&fit=crop',
    menuContext: ['a_la_carte'],
    sustainability: {
      lowCarbon: false,
      seasonal: false,
      zeroWaste: true,
      score: 64,
    },
    rating: 4.9,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'recipe-10',
    title: 'Ceviche Classico with Leche de Tigre',
    chef: MOCK_CHEFS[9],
    restaurant: 'Hiša Franko',
    description: 'Pristine white fish cured in citrus and spices, Peruvian-style with traditional tiger milk sauce.',
    cuisines: [
      { id: 'peruvian', name: 'Peruvian', parent: 'south_american' },
      { id: 'latin_american', name: 'Latin American', parent: 'latin' },
    ],
    techniques: [
      { id: 'curing', name: 'Curing', category: 'preservation', description: 'Preserving with salt and spices' },
    ],
    station: { id: 'garde_manger', name: 'Garde Manger', description: 'Cold station' },
    difficulty: 'intermediate',
    prepTime: 30,
    cookTime: 0,
    servings: 4,
    ingredients: [
      { id: 'i67', name: 'Fresh White Fish', weight: 600, unit: 'g', allergens: ['fish'], group: 'protein', sustainability: 'seasonal' },
      { id: 'i68', name: 'Lime Juice', weight: 200, unit: 'ml', allergens: [], group: 'fruit', sustainability: 'seasonal' },
      { id: 'i69', name: 'Fish Stock', weight: 100, unit: 'ml', allergens: ['fish'], group: 'other', sustainability: 'standard' },
      { id: 'i70', name: 'Ají Amarillo', weight: 50, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'seasonal' },
      { id: 'i71', name: 'Red Onion', weight: 150, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'seasonal' },
      { id: 'i72', name: 'Cilantro', weight: 30, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'seasonal' },
      { id: 'i73', name: 'Corn Tortillas', weight: 200, unit: 'g', allergens: ['cereals'], group: 'grain', sustainability: 'standard' },
      { id: 'i74', name: 'Sea Salt', weight: 8, unit: 'g', allergens: [], group: 'seasoning', sustainability: 'standard' },
    ],
    steps: [
      {
        id: 's45',
        order: 1,
        instruction: 'Dice fresh white fish into uniform 1cm cubes.',
        techniques: [],
        station: { id: 'garde_manger', name: 'Garde Manger', description: 'Cold station' },
        duration: 10,
      },
      {
        id: 's46',
        order: 2,
        instruction: 'Make leche de tigre: puree ají amarillo with lime juice and fish stock.',
        techniques: [],
        station: null,
        duration: 5,
      },
      {
        id: 's47',
        order: 3,
        instruction: 'Marinate fish in leche de tigre for 8-10 minutes, fold in red onion and cilantro.',
        techniques: ['curing'],
        station: { id: 'garde_manger', name: 'Garde Manger', description: 'Cold station' },
        duration: 10,
      },
      {
        id: 's48',
        order: 4,
        instruction: 'Serve immediately with warm corn tortillas and lime wedges.',
        techniques: [],
        station: { id: 'garde_manger', name: 'Garde Manger', description: 'Cold station' },
        duration: 2,
      },
    ],
    allergens: [
      { id: 'fish', name: 'Fish', code: 'fish' },
      { id: 'cereals', name: 'Cereals containing gluten', code: 'gluten' },
    ],
    foodCostPercent: 32,
    image: 'https://images.unsplash.com/photo-1535399831218-d5bd36d1a6b3?w=800&h=600&fit=crop',
    menuContext: ['a_la_carte', 'brunch'],
    sustainability: {
      lowCarbon: true,
      seasonal: true,
      zeroWaste: false,
      score: 76,
    },
    rating: 4.8,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'recipe-11',
    title: 'Thai Green Curry with Coconut Milk',
    chef: MOCK_CHEFS[0],
    restaurant: 'Osteria Francescana',
    description: 'Aromatic Thai green curry with fresh basil, tender chicken, and creamy coconut broth.',
    cuisines: [
      { id: 'thai', name: 'Thai', parent: 'asian' },
      { id: 'southeast_asian', name: 'Southeast Asian', parent: 'asian' },
    ],
    techniques: [
      { id: 'simmering', name: 'Simmering', category: 'wet_heat', description: 'Cooking in gently bubbling liquid' },
      { id: 'curry_making', name: 'Curry Making', category: 'wet_heat', description: 'Traditional curry preparation' },
    ],
    station: { id: 'saucier', name: 'Saucier', description: 'Sauce station' },
    difficulty: 'intermediate',
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    ingredients: [
      { id: 'i75', name: 'Chicken Breast', weight: 600, unit: 'g', allergens: [], group: 'protein', sustainability: 'standard' },
      { id: 'i76', name: 'Thai Green Chili', weight: 60, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'seasonal' },
      { id: 'i77', name: 'Coconut Milk', weight: 400, unit: 'ml', allergens: [], group: 'other', sustainability: 'standard' },
      { id: 'i78', name: 'Thai Basil', weight: 20, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'seasonal' },
      { id: 'i79', name: 'Lemongrass', weight: 30, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'seasonal' },
      { id: 'i80', name: 'Galangal', weight: 20, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'seasonal' },
      { id: 'i81', name: 'Fish Sauce', weight: 20, unit: 'ml', allergens: ['fish'], group: 'seasoning', sustainability: 'standard' },
      { id: 'i82', name: 'Palm Sugar', weight: 15, unit: 'g', allergens: [], group: 'seasoning', sustainability: 'standard' },
    ],
    steps: [
      {
        id: 's49',
        order: 1,
        instruction: 'Make curry paste: blend green chilies, lemongrass, and galangal.',
        techniques: [],
        station: null,
        duration: 8,
      },
      {
        id: 's50',
        order: 2,
        instruction: 'Heat coconut milk, add curry paste, simmer for 3 minutes.',
        techniques: ['simmering'],
        station: { id: 'saucier', name: 'Saucier', description: 'Sauce station' },
        duration: 8,
      },
      {
        id: 's51',
        order: 3,
        instruction: 'Add sliced chicken breast, simmer until cooked through, approximately 12 minutes.',
        techniques: ['simmering'],
        station: { id: 'saucier', name: 'Saucier', description: 'Sauce station' },
        duration: 12,
      },
      {
        id: 's52',
        order: 4,
        instruction: 'Finish with fish sauce, palm sugar, and fresh Thai basil.',
        techniques: [],
        station: { id: 'saucier', name: 'Saucier', description: 'Sauce station' },
        duration: 2,
      },
    ],
    allergens: [
      { id: 'fish', name: 'Fish', code: 'fish' },
    ],
    foodCostPercent: 24,
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&h=600&fit=crop',
    menuContext: ['a_la_carte'],
    sustainability: {
      lowCarbon: false,
      seasonal: true,
      zeroWaste: false,
      score: 61,
    },
    rating: 4.7,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'recipe-12',
    title: 'Paella Valenciana with Bomba Rice',
    chef: MOCK_CHEFS[1],
    restaurant: 'Noma',
    description: 'Authentic Spanish paella with saffron, bomba rice, rabbit, and snails in a traditional clay pan.',
    cuisines: [
      { id: 'spanish', name: 'Spanish', parent: 'european' },
      { id: 'mediterranean', name: 'Mediterranean', parent: 'european' },
    ],
    techniques: [
      { id: 'simmering', name: 'Simmering', category: 'wet_heat', description: 'Cooking in gently bubbling liquid' },
      { id: 'pan_frying', name: 'Pan-Frying', category: 'dry_heat', description: 'Cooking in a shallow pan with oil' },
    ],
    station: { id: 'rotisseur', name: 'Rôtisseur', description: 'Roast station' },
    difficulty: 'advanced',
    prepTime: 25,
    cookTime: 40,
    servings: 6,
    ingredients: [
      { id: 'i83', name: 'Bomba Rice', weight: 400, unit: 'g', allergens: [], group: 'grain', sustainability: 'standard' },
      { id: 'i84', name: 'Rabbit Meat', weight: 600, unit: 'g', allergens: [], group: 'protein', sustainability: 'standard' },
      { id: 'i85', name: 'Large Snails', weight: 300, unit: 'g', allergens: ['mollusks'], group: 'protein', sustainability: 'standard' },
      { id: 'i86', name: 'Saffron', weight: 1, unit: 'g', allergens: [], group: 'seasoning', sustainability: 'standard' },
      { id: 'i87', name: 'Chicken Stock', weight: 1000, unit: 'ml', allergens: [], group: 'other', sustainability: 'standard' },
      { id: 'i88', name: 'Olive Oil', weight: 100, unit: 'ml', allergens: [], group: 'oil', sustainability: 'local' },
      { id: 'i89', name: 'Green Beans', weight: 150, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'seasonal' },
      { id: 'i90', name: 'Paprika', weight: 10, unit: 'g', allergens: [], group: 'seasoning', sustainability: 'standard' },
    ],
    steps: [
      {
        id: 's53',
        order: 1,
        instruction: 'Heat stock with saffron and keep warm.',
        techniques: [],
        station: null,
        duration: 10,
      },
      {
        id: 's54',
        order: 2,
        instruction: 'Brown rabbit and snails in paella pan with olive oil, remove.',
        techniques: ['pan_frying'],
        station: { id: 'rotisseur', name: 'Rôtisseur', description: 'Roast station' },
        duration: 10,
      },
      {
        id: 's55',
        order: 3,
        instruction: 'Toast bomba rice briefly, add saffron stock gradually.',
        techniques: ['simmering'],
        station: { id: 'rotisseur', name: 'Rôtisseur', description: 'Roast station' },
        duration: 25,
      },
      {
        id: 's56',
        order: 4,
        instruction: 'Return rabbit and snails to pan with green beans, cook until rice is tender.',
        techniques: ['simmering'],
        station: { id: 'rotisseur', name: 'Rôtisseur', description: 'Roast station' },
        duration: 8,
      },
    ],
    allergens: [
      { id: 'mollusks', name: 'Mollusks', code: 'mollusks' },
    ],
    foodCostPercent: 34,
    image: 'https://images.unsplash.com/photo-1534080564583-6be75777b70a?w=800&h=600&fit=crop',
    menuContext: ['a_la_carte', 'tasting_menu'],
    sustainability: {
      lowCarbon: false,
      seasonal: true,
      zeroWaste: false,
      score: 67,
    },
    rating: 4.8,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'recipe-13',
    title: 'Korean Bibimbap with Gochujang',
    chef: MOCK_CHEFS[2],
    restaurant: 'Gaggan',
    description: 'Mixed vegetables, egg, and beef over warm rice with spicy gochujang sauce in a sizzling stone bowl.',
    cuisines: [
      { id: 'korean', name: 'Korean', parent: 'asian' },
      { id: 'east_asian', name: 'East Asian', parent: 'asian' },
    ],
    techniques: [
      { id: 'pan_frying', name: 'Pan-Frying', category: 'dry_heat', description: 'Cooking in a shallow pan with oil' },
      { id: 'stir_frying', name: 'Stir-Frying', category: 'dry_heat', description: 'Quick cooking with constant stirring' },
    ],
    station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
    difficulty: 'intermediate',
    prepTime: 25,
    cookTime: 15,
    servings: 4,
    ingredients: [
      { id: 'i91', name: 'Short Grain Rice', weight: 400, unit: 'g', allergens: [], group: 'grain', sustainability: 'standard' },
      { id: 'i92', name: 'Beef Sirloin', weight: 400, unit: 'g', allergens: [], group: 'protein', sustainability: 'standard' },
      { id: 'i93', name: 'Gochujang', weight: 60, unit: 'g', allergens: ['soy', 'wheat'], group: 'seasoning', sustainability: 'standard' },
      { id: 'i94', name: 'Spinach', weight: 200, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'seasonal' },
      { id: 'i95', name: 'Bean Sprouts', weight: 150, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'seasonal' },
      { id: 'i96', name: 'Shiitake Mushrooms', weight: 150, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'seasonal' },
      { id: 'i97', name: 'Egg', weight: 120, unit: 'g', allergens: ['eggs'], group: 'protein', sustainability: 'standard' },
      { id: 'i98', name: 'Sesame Oil', weight: 30, unit: 'ml', allergens: ['sesame'], group: 'oil', sustainability: 'standard' },
    ],
    steps: [
      {
        id: 's57',
        order: 1,
        instruction: 'Cook short grain rice and divide into stone bowls.',
        techniques: [],
        station: null,
        duration: 15,
      },
      {
        id: 's58',
        order: 2,
        instruction: 'Marinate and quickly pan-fry beef sirloin, set aside.',
        techniques: ['pan_frying'],
        station: { id: 'rotisseur', name: 'Rôtisseur', description: 'Roast station' },
        duration: 8,
      },
      {
        id: 's59',
        order: 3,
        instruction: 'Blanch spinach and bean sprouts, stir-fry mushrooms separately.',
        techniques: ['stir_frying'],
        station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
        duration: 10,
      },
      {
        id: 's60',
        order: 4,
        instruction: 'Arrange vegetables and beef on rice, top with fried egg and gochujang sauce.',
        techniques: [],
        station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
        duration: 3,
      },
    ],
    allergens: [
      { id: 'soy', name: 'Soy', code: 'soy' },
      { id: 'wheat', name: 'Wheat', code: 'wheat' },
      { id: 'eggs', name: 'Eggs', code: 'eggs' },
      { id: 'sesame', name: 'Sesame', code: 'sesame' },
    ],
    foodCostPercent: 26,
    image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=800&h=600&fit=crop',
    menuContext: ['a_la_carte'],
    sustainability: {
      lowCarbon: false,
      seasonal: true,
      zeroWaste: false,
      score: 62,
    },
    rating: 4.7,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'recipe-14',
    title: 'Prime Rib with Yorkshire Pudding',
    chef: MOCK_CHEFS[3],
    restaurant: 'The French Laundry',
    description: 'Perfectly roasted prime rib with crispy herbs and dramatic Yorkshire pudding, a British classic.',
    cuisines: [
      { id: 'british', name: 'British', parent: 'european' },
    ],
    techniques: [
      { id: 'roasting', name: 'Roasting', category: 'dry_heat', description: 'Cooking with dry heat in an oven' },
      { id: 'baking', name: 'Baking', category: 'dry_heat', description: 'Cooking with dry heat at specific temperatures' },
    ],
    station: { id: 'rotisseur', name: 'Rôtisseur', description: 'Roast station' },
    difficulty: 'advanced',
    prepTime: 30,
    cookTime: 150,
    servings: 8,
    ingredients: [
      { id: 'i99', name: 'Prime Rib', weight: 2400, unit: 'g', allergens: [], group: 'protein', sustainability: 'standard' },
      { id: 'i100', name: 'Fresh Thyme', weight: 20, unit: 'g', allergens: [], group: 'seasoning', sustainability: 'seasonal' },
      { id: 'i101', name: 'Rosemary', weight: 15, unit: 'g', allergens: [], group: 'seasoning', sustainability: 'seasonal' },
      { id: 'i102', name: 'Garlic Cloves', weight: 40, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'standard' },
      { id: 'i103', name: 'Beef Stock', weight: 300, unit: 'ml', allergens: [], group: 'other', sustainability: 'standard' },
      { id: 'i104', name: 'Eggs', weight: 180, unit: 'g', allergens: ['eggs'], group: 'protein', sustainability: 'standard' },
      { id: 'i105', name: 'Flour', weight: 150, unit: 'g', allergens: ['cereals'], group: 'grain', sustainability: 'standard' },
      { id: 'i106', name: 'Whole Milk', weight: 300, unit: 'ml', allergens: ['milk'], group: 'dairy', sustainability: 'standard' },
    ],
    steps: [
      {
        id: 's61',
        order: 1,
        instruction: 'Season prime rib generously and bring to room temperature for 1 hour.',
        techniques: [],
        station: null,
        duration: 60,
      },
      {
        id: 's62',
        order: 2,
        instruction: 'Sear meat on all sides until deeply browned.',
        techniques: [],
        station: { id: 'rotisseur', name: 'Rôtisseur', description: 'Roast station' },
        duration: 12,
      },
      {
        id: 's63',
        order: 3,
        instruction: 'Roast at 120°C until internal temperature reaches 55°C for medium-rare (about 2 hours).',
        techniques: ['roasting'],
        station: { id: 'rotisseur', name: 'Rôtisseur', description: 'Roast station' },
        duration: 120,
      },
      {
        id: 's64',
        order: 4,
        instruction: 'Rest meat for 15 minutes. Meanwhile, make Yorkshire pudding batter and bake at 220°C for 20 minutes.',
        techniques: ['baking'],
        station: { id: 'patissier', name: 'Pâtissier', description: 'Pastry station' },
        duration: 20,
      },
    ],
    allergens: [
      { id: 'eggs', name: 'Eggs', code: 'eggs' },
      { id: 'cereals', name: 'Cereals containing gluten', code: 'gluten' },
      { id: 'milk', name: 'Milk (including lactose)', code: 'milk' },
    ],
    foodCostPercent: 44,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&h=600&fit=crop',
    menuContext: ['tasting_menu', 'a_la_carte'],
    sustainability: {
      lowCarbon: false,
      seasonal: false,
      zeroWaste: false,
      score: 45,
    },
    rating: 4.9,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'recipe-15',
    title: 'Dim Sum Selection - Siu Mai and Har Gow',
    chef: MOCK_CHEFS[4],
    restaurant: 'Core by Clare Smyth',
    description: 'Traditional Cantonese dim sum: steamed pork dumplings (siu mai) and shrimp dumplings (har gow).',
    cuisines: [
      { id: 'chinese', name: 'Chinese', parent: 'asian' },
      { id: 'cantonese', name: 'Cantonese', parent: 'chinese' },
    ],
    techniques: [
      { id: 'steaming', name: 'Steaming', category: 'wet_heat', description: 'Cooking with steam' },
      { id: 'folding', name: 'Folding', category: 'pastry', description: 'Shaping dumpling wrappers' },
    ],
    station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
    difficulty: 'advanced',
    prepTime: 40,
    cookTime: 15,
    servings: 6,
    ingredients: [
      { id: 'i107', name: 'Ground Pork', weight: 300, unit: 'g', allergens: [], group: 'protein', sustainability: 'standard' },
      { id: 'i108', name: 'Fresh Shrimp', weight: 250, unit: 'g', allergens: ['crustaceans'], group: 'protein', sustainability: 'seasonal' },
      { id: 'i109', name: 'Wonton Wrappers', weight: 200, unit: 'g', allergens: ['cereals', 'eggs'], group: 'grain', sustainability: 'standard' },
      { id: 'i110', name: 'Bamboo Shoots', weight: 100, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'standard' },
      { id: 'i111', name: 'Water Chestnut', weight: 80, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'standard' },
      { id: 'i112', name: 'Soy Sauce', weight: 30, unit: 'ml', allergens: ['soy'], group: 'seasoning', sustainability: 'standard' },
      { id: 'i113', name: 'Sesame Oil', weight: 10, unit: 'ml', allergens: ['sesame'], group: 'oil', sustainability: 'standard' },
      { id: 'i114', name: 'Ginger', weight: 20, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'seasonal' },
    ],
    steps: [
      {
        id: 's65',
        order: 1,
        instruction: 'Finely chop bamboo shoots and water chestnuts for siu mai filling.',
        techniques: [],
        station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
        duration: 8,
      },
      {
        id: 's66',
        order: 2,
        instruction: 'Mix ground pork with bamboo shoots, water chestnut, soy sauce, and sesame oil.',
        techniques: [],
        station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
        duration: 5,
      },
      {
        id: 's67',
        order: 3,
        instruction: 'Fold siu mai wrappers into traditional purse shape, top with pork mixture.',
        techniques: ['folding'],
        station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
        duration: 15,
      },
      {
        id: 's68',
        order: 4,
        instruction: 'Fold har gow wrappers into crescent with shrimp and bamboo shoots.',
        techniques: ['folding'],
        station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
        duration: 15,
      },
      {
        id: 's69',
        order: 5,
        instruction: 'Steam both types of dumplings in bamboo steamer for 8-10 minutes.',
        techniques: ['steaming'],
        station: { id: 'saucier', name: 'Saucier', description: 'Sauce station' },
        duration: 9,
      },
    ],
    allergens: [
      { id: 'crustaceans', name: 'Crustaceans', code: 'crustaceans' },
      { id: 'cereals', name: 'Cereals containing gluten', code: 'gluten' },
      { id: 'eggs', name: 'Eggs', code: 'eggs' },
      { id: 'soy', name: 'Soy', code: 'soy' },
      { id: 'sesame', name: 'Sesame', code: 'sesame' },
    ],
    foodCostPercent: 28,
    image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=800&h=600&fit=crop',
    menuContext: ['a_la_carte', 'brunch'],
    sustainability: {
      lowCarbon: true,
      seasonal: true,
      zeroWaste: false,
      score: 71,
    },
    rating: 4.8,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

MOCK_RECIPES.forEach((recipe) => {
  const chef = MOCK_CHEFS.find((c) => c.id === recipe.chef.id);
  if (chef) {
    chef.recipes.push(recipe);
  }
});

export const MOCK_MASTERCLASSES: Masterclass[] = [
  // Original 2 masterclasses
  {
    id: 'mc-1',
    title: 'Modern Italian Cooking Fundamentals',
    chef: MOCK_CHEFS[0],
    description: 'Master the techniques behind contemporary Italian cuisine with Massimo Bottura. Learn how tradition meets innovation.',
    image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&h=600&fit=crop',
    level: 'intermediate',
    cuisine: ['Italian', 'Modern European'],
    duration: 180,
    price: 299,
    episodes: [
      {
        id: 'ep-1',
        order: 1,
        title: 'Introduction to Modernist Techniques',
        description: 'Explore the philosophy behind modern Italian cooking and essential modernist methods.',
        duration: 45,
        relatedRecipeIds: ['recipe-1'],
      },
      {
        id: 'ep-2',
        order: 2,
        title: 'Risotto Mastery',
        description: 'Perfect your risotto technique with detailed guidance on texture and flavor balance.',
        duration: 60,
        relatedRecipeIds: ['recipe-1'],
      },
      {
        id: 'ep-3',
        order: 3,
        title: 'Molecular Emulsions and Foams',
        description: 'Create stunning emulsions and foams to elevate your presentations.',
        duration: 75,
        relatedRecipeIds: [],
      },
    ],
    rating: 4.8,
    enrollmentCount: 1243,
    createdAt: new Date(),
  },
  {
    id: 'mc-2',
    title: 'Nordic Foraging and Sustainable Cooking',
    chef: MOCK_CHEFS[1],
    description: 'Join René Redzepi in exploring Nordic cuisine through foraging, seasonality, and sustainable practices.',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=600&fit=crop',
    level: 'advanced',
    cuisine: ['Nordic', 'Scandinavian'],
    duration: 240,
    price: 449,
    episodes: [
      {
        id: 'ep-4',
        order: 1,
        title: 'Foraging Essentials',
        description: 'Learn to identify and responsibly harvest wild ingredients for your kitchen.',
        duration: 60,
        relatedRecipeIds: ['recipe-2'],
      },
      {
        id: 'ep-5',
        order: 2,
        title: 'Seasonal Menu Planning',
        description: 'Structure menus around seasonal availability and optimize ingredient usage.',
        duration: 60,
        relatedRecipeIds: [],
      },
      {
        id: 'ep-6',
        order: 3,
        title: 'Zero Waste Cooking',
        description: 'Minimize waste through creative utilization of every ingredient component.',
        duration: 60,
        relatedRecipeIds: ['recipe-2'],
      },
      {
        id: 'ep-7',
        order: 4,
        title: 'Traditional Preservation Techniques',
        description: 'Master curing, fermentation, and drying to extend ingredient seasons.',
        duration: 60,
        relatedRecipeIds: [],
      },
    ],
    rating: 4.9,
    enrollmentCount: 2156,
    createdAt: new Date(),
  },
  // New 3 masterclasses
  {
    id: 'mc-3',
    title: 'Contemporary French Technique Masterclass',
    chef: MOCK_CHEFS[7],
    description: 'With Dominique Crenn: Learn poetic plating and contemporary French techniques that define modern gastronomy.',
    image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800&h=600&fit=crop',
    level: 'advanced',
    cuisine: ['French', 'Modern European'],
    duration: 210,
    price: 399,
    episodes: [
      {
        id: 'ep-8',
        order: 1,
        title: 'Classical French Foundations',
        description: 'Master the essential techniques of French cuisine that form the foundation of all great cooking.',
        duration: 60,
        relatedRecipeIds: ['recipe-4', 'recipe-6'],
      },
      {
        id: 'ep-9',
        order: 2,
        title: 'Poetic Plating and Presentation',
        description: 'Learn the art of beautiful plate design and tell stories through your presentations.',
        duration: 50,
        relatedRecipeIds: [],
      },
      {
        id: 'ep-10',
        order: 3,
        title: 'Innovation within Tradition',
        description: 'Discover how to break traditional rules while respecting the craft.',
        duration: 50,
        relatedRecipeIds: ['recipe-8'],
      },
      {
        id: 'ep-11',
        order: 4,
        title: 'Building Your Culinary Voice',
        description: 'Develop your unique style as a chef and express yourself through food.',
        duration: 50,
        relatedRecipeIds: [],
      },
    ],
    rating: 4.9,
    enrollmentCount: 1876,
    createdAt: new Date(),
  },
  {
    id: 'mc-4',
    title: 'Japanese Culinary Excellence and Sustainability',
    chef: MOCK_CHEFS[8],
    description: 'With Yoshihiro Narisawa: Explore contemporary Japanese techniques with deep respect for ingredient sourcing and sustainability.',
    image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&h=600&fit=crop',
    level: 'intermediate',
    cuisine: ['Japanese', 'Contemporary Asian'],
    duration: 190,
    price: 349,
    episodes: [
      {
        id: 'ep-12',
        order: 1,
        title: 'Fundamentals of Japanese Culinary Philosophy',
        description: 'Understand washoku principles and the philosophy of Japanese cooking.',
        duration: 50,
        relatedRecipeIds: ['recipe-9'],
      },
      {
        id: 'ep-13',
        order: 2,
        title: 'Knife Skills and Precision',
        description: 'Master Japanese knife techniques and precision cuts essential to the cuisine.',
        duration: 50,
        relatedRecipeIds: [],
      },
      {
        id: 'ep-14',
        order: 3,
        title: 'Sourcing and Sustainability',
        description: 'Learn how to source premium ingredients responsibly while supporting sustainability.',
        duration: 45,
        relatedRecipeIds: [],
      },
      {
        id: 'ep-15',
        order: 4,
        title: 'Contemporary Japanese Innovation',
        description: 'Explore modern interpretations of traditional Japanese techniques.',
        duration: 45,
        relatedRecipeIds: [],
      },
    ],
    rating: 4.8,
    enrollmentCount: 1624,
    createdAt: new Date(),
  },
  {
    id: 'mc-5',
    title: 'Global Cuisines: A Journey Through World Flavors',
    chef: MOCK_CHEFS[5],
    description: 'With Alain Ducasse: Travel through the worlds greatest cuisines, learning techniques from Mediterranean, Asian, and Latin American traditions.',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=600&fit=crop',
    level: 'intermediate',
    cuisine: ['Global', 'Mediterranean', 'Asian', 'Latin American'],
    duration: 220,
    price: 379,
    episodes: [
      {
        id: 'ep-16',
        order: 1,
        title: 'Mediterranean Flavors and Ingredients',
        description: 'Explore the sun-drenched flavors of Mediterranean cuisine and ingredient sourcing.',
        duration: 55,
        relatedRecipeIds: ['recipe-12'],
      },
      {
        id: 'ep-17',
        order: 2,
        title: 'Asian Techniques and Balance',
        description: 'Learn the balance of flavors and techniques that define Asian cuisines.',
        duration: 55,
        relatedRecipeIds: ['recipe-11', 'recipe-15'],
      },
      {
        id: 'ep-18',
        order: 3,
        title: 'Latin American Bold Flavors',
        description: 'Discover the vibrant and bold flavors of Latin American cooking traditions.',
        duration: 55,
        relatedRecipeIds: ['recipe-10'],
      },
      {
        id: 'ep-19',
        order: 4,
        title: 'Building Menus with Global Inspirations',
        description: 'Create balanced menus that blend global inspirations with your unique voice.',
        duration: 55,
        relatedRecipeIds: [],
      },
    ],
    rating: 4.7,
    enrollmentCount: 1245,
    createdAt: new Date(),
  },
];

MOCK_CHEFS.forEach((chef) => {
  const masterclasses = MOCK_MASTERCLASSES.filter((mc) => mc.chef.id === chef.id);
  chef.masterclasses = masterclasses;
});

export const MOCK_JOBS: Job[] = [
  // Original 2 jobs
  {
    id: 'job-1',
    title: 'Head Chef',
    restaurant: '1-Altitude',
    position: 'Head Chef',
    cuisine: ['French', 'Contemporary'],
    location: 'Singapore',
    salary: { min: 120000, max: 180000, currency: 'SGD' },
    description: 'We are seeking an experienced Head Chef to lead our kitchen team of 12 chefs at 1-Altitude.',
    requirements: [
      'Minimum 10 years executive kitchen experience',
      '3+ Michelin stars or equivalent accolades',
      'French classical training',
      'Team leadership experience',
    ],
    experienceLevel: 'executive',
    type: 'full_time',
    postedDate: new Date(),
    deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'job-2',
    title: 'Sous Chef - Pastry',
    restaurant: 'Oumi',
    position: 'Sous Chef - Pastry',
    cuisine: ['Pastry', 'Bakery'],
    location: 'Singapore',
    salary: { min: 60000, max: 80000, currency: 'SGD' },
    description: 'Join our pastry team as a Sous Chef at Oumi. Create stunning desserts and bread products.',
    requirements: [
      'Pastry diploma or equivalent',
      '5+ years pastry experience',
      'Knowledge of lamination and tempering',
      'Production management experience',
    ],
    experienceLevel: 'mid',
    type: 'full_time',
    postedDate: new Date(),
  },
  // New 4 jobs
  {
    id: 'job-3',
    title: 'Executive Sous Chef',
    restaurant: 'Kaarla',
    position: 'Executive Sous Chef',
    cuisine: ['Nordic', 'Contemporary'],
    location: 'Singapore',
    salary: { min: 80000, max: 120000, currency: 'SGD' },
    description: 'Lead kitchen operations at Kaarla as Executive Sous Chef. Manage food quality and team coordination.',
    requirements: [
      'Minimum 8 years kitchen experience',
      '2+ Michelin stars or equivalent',
      'Nordic cuisine expertise',
      'Strong management skills',
    ],
    experienceLevel: 'senior',
    type: 'full_time',
    postedDate: new Date(),
    deadline: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'job-4',
    title: 'Chef de Partie - Saucier',
    restaurant: 'Sol & Luna',
    position: 'Chef de Partie - Saucier',
    cuisine: ['French', 'Mediterranean'],
    location: 'Singapore',
    salary: { min: 48000, max: 65000, currency: 'SGD' },
    description: 'Join our sauce station at Sol & Luna. Create beautiful classical and contemporary sauces.',
    requirements: [
      'Minimum 5 years sauce station experience',
      'Strong French technique knowledge',
      'Understanding of flavor balance',
      'Team collaboration skills',
    ],
    experienceLevel: 'mid',
    type: 'full_time',
    postedDate: new Date(),
  },
  {
    id: 'job-5',
    title: 'Restaurant Manager',
    restaurant: 'Camille',
    position: 'Restaurant Manager',
    cuisine: ['Global', 'Contemporary'],
    location: 'Singapore',
    salary: { min: 55000, max: 75000, currency: 'SGD' },
    description: 'Manage front-of-house operations at Camille. Oversee guest experience and dining room staff.',
    requirements: [
      'Minimum 6 years restaurant management experience',
      'Proficiency in restaurant management systems',
      'Excellent customer service skills',
      'Staff training and development experience',
    ],
    experienceLevel: 'mid',
    type: 'full_time',
    postedDate: new Date(),
  },
  {
    id: 'job-6',
    title: 'Sommelier',
    restaurant: '1-Altitude',
    position: 'Sommelier',
    cuisine: ['Wine & Beverages'],
    location: 'Singapore',
    salary: { min: 48000, max: 70000, currency: 'SGD' },
    description: 'Join 1-Altitude as our Sommelier. Curate wine pairings and manage beverage program.',
    requirements: [
      'WSET Level 3 or higher certification',
      'Minimum 4 years sommelier or beverage experience',
      'Wine pairing expertise',
      'Knowledge of fine dining service',
    ],
    experienceLevel: 'mid',
    type: 'full_time',
    postedDate: new Date(),
    deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
  },
];

export const MOCK_SUPPLIERS: Supplier[] = [
  // Original 3 suppliers
  {
    id: 'sup-1',
    name: 'Premium Seafood Wholesale',
    type: ['Fish', 'Shellfish', 'Seafood'],
    description: 'Premium wild-caught and responsibly farmed seafood sourced directly from sustainable fisheries.',
    location: 'Singapore',
    rating: 4.8,
    specialties: ['Wild-caught fish', 'Live lobster', 'Scallops', 'Oysters'],
    verified: true,
    website: 'https://example.com',
    createdAt: new Date(),
  },
  {
    id: 'sup-2',
    name: 'Organic Farm Collective',
    type: ['Vegetables', 'Fruits', 'Herbs'],
    description: 'Seasonal organic produce from local farms in the region, delivered fresh daily.',
    location: 'Singapore',
    rating: 4.7,
    specialties: ['Organic vegetables', 'Heirloom varieties', 'Microgreens', 'Edible flowers'],
    verified: true,
    website: 'https://example.com',
    createdAt: new Date(),
  },
  {
    id: 'sup-3',
    name: 'Heritage Grain Mill',
    type: ['Grains', 'Flour', 'Bread'],
    description: 'Artisanal grains and flours milled to order for the finest bakers and chefs.',
    location: 'Singapore',
    rating: 4.9,
    specialties: ['Heritage grains', 'Custom milling', 'Sourdough cultures', 'Specialty flours'],
    verified: true,
    createdAt: new Date(),
  },
  // New 3 suppliers
  {
    id: 'sup-4',
    name: 'Artisan Dairy & Cheese',
    type: ['Dairy', 'Cheese', 'Butter'],
    description: 'Small-batch artisan cheeses, butter, and dairy products from family farms. Strict quality standards.',
    location: 'Singapore',
    rating: 4.9,
    specialties: ['Aged cheeses', 'Raw milk varieties', 'Artisan butter', 'Specialty dairy'],
    verified: true,
    website: 'https://example.com',
    createdAt: new Date(),
  },
  {
    id: 'sup-5',
    name: 'Asian Specialty Imports',
    type: ['Asian Ingredients', 'Spices', 'Condiments'],
    description: 'Premium Asian ingredients sourced directly from specialty producers across Asia.',
    location: 'Singapore',
    rating: 4.6,
    specialties: ['Japanese ingredients', 'Asian spices', 'Traditional sauces', 'Specialty pastes'],
    verified: true,
    website: 'https://example.com',
    createdAt: new Date(),
  },
  {
    id: 'sup-6',
    name: 'Fine Wines & Spirits',
    type: ['Wine', 'Spirits', 'Beverages'],
    description: 'Curated selection of fine wines, spirits, and rare beverages for discerning chefs.',
    location: 'Singapore',
    rating: 4.8,
    specialties: ['Bordeaux', 'Burgundy', 'Fine spirits', 'Rare wines'],
    verified: true,
    website: 'https://example.com',
    createdAt: new Date(),
  },
];
