import { Recipe, Chef, Masterclass, Job, Supplier, Episode } from '@/types/index';

export const MOCK_CHEFS: Chef[] = [
  {
    id: 'chef-1',
    name: 'Massimo Bottura',
    avatar: 'https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=400&h=400&fit=crop',
    bio: 'Three-Michelin-starred chef and innovator of modern Italian cuisine. Known for transforming traditional dishes with contemporary techniques.',
    cuisine: ['Italian', 'Modern European'],
    accolades: [
      { type: 'michelin', stars: 3, year: 2023, restaurant: 'Osteria Francescana' },
      { type: 'fifty_best', year: 2023 },
    ],
    restaurant: 'Osteria Francescana',
    yearsExperience: 35,
    specialties: ['Modernist Cooking', 'Italian Cuisine', 'Molecular Gastronomy'],
    recipes: [],
    masterclasses: [],
    createdAt: new Date(),
  },
  {
    id: 'chef-2',
    name: 'René Redzepi',
    avatar: 'https://images.unsplash.com/photo-1504674900152-b8b80e7b6c5d?w=400&h=400&fit=crop',
    bio: 'Pioneer of New Nordic Cuisine. Focuses on hyper-local, seasonal ingredients and sustainable practices.',
    cuisine: ['Nordic', 'Scandinavian'],
    accolades: [
      { type: 'michelin', stars: 3, year: 2023, restaurant: 'Noma' },
      { type: 'fifty_best', year: 2023 },
    ],
    restaurant: 'Noma',
    yearsExperience: 30,
    specialties: ['Nordic Cuisine', 'Foraging', 'Sustainability'],
    recipes: [],
    masterclasses: [],
    createdAt: new Date(),
  },
  {
    id: 'chef-3',
    name: 'Gaggan Anand',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    bio: 'Visionary chef redefining modern Indian cuisine with progressive techniques and emotional storytelling through food.',
    cuisine: ['Indian', 'Contemporary'],
    accolades: [
      { type: 'michelin', stars: 2, year: 2023, restaurant: 'Gaggan' },
      { type: 'fifty_best', year: 2023 },
    ],
    restaurant: 'Gaggan',
    yearsExperience: 28,
    specialties: ['Contemporary Indian', 'Molecular Gastronomy', 'Culinary Art'],
    recipes: [],
    masterclasses: [],
    createdAt: new Date(),
  },
  {
    id: 'chef-4',
    name: 'Thomas Keller',
    avatar: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&h=400&fit=crop',
    bio: 'Master of French classical technique. Renowned for precise, elegant cuisine with impeccable execution.',
    cuisine: ['French', 'American Contemporary'],
    accolades: [
      { type: 'michelin', stars: 3, year: 2023, restaurant: 'The French Laundry' },
      { type: 'fifty_best', year: 2023 },
    ],
    restaurant: 'The French Laundry',
    yearsExperience: 40,
    specialties: ['French Cuisine', 'Classical Technique', 'Fine Dining'],
    recipes: [],
    masterclasses: [],
    createdAt: new Date(),
  },
  {
    id: 'chef-5',
    name: 'Clare Smyth',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
    bio: 'Chef-patron of the acclaimed restaurant Core. Specializes in innovative British cuisine with Japanese influences.',
    cuisine: ['British', 'Japanese Fusion'],
    accolades: [
      { type: 'michelin', stars: 2, year: 2023, restaurant: 'Core by Clare Smyth' },
    ],
    restaurant: 'Core by Clare Smyth',
    yearsExperience: 25,
    specialties: ['British Cuisine', 'Japanese Techniques', 'Innovation'],
    recipes: [],
    masterclasses: [],
    createdAt: new Date(),
  },
];

export const MOCK_RECIPES: Recipe[] = [
  {
    id: 'recipe-1',
    title: 'Risotto ai Funghi Porcini',
    chef: MOCK_CHEFS[0],
    restaurant: 'Osteria Francescana',
    description: 'Creamy arborio rice with wild porcini mushrooms, perfectly balanced with truffle oil and Parmigiano-Reggiano.',
    cuisines: [
      { id: 'italian', name: 'Italian', parent: 'european' },
      { id: 'italian_northern', name: 'Northern Italian', parent: 'italian' },
    ],
    techniques: [
      { id: 'simmering', name: 'Simmering', category: 'wet_heat', description: 'Cooking in gently bubbling liquid' },
      { id: 'pan_frying', name: 'Pan-Frying', category: 'dry_heat', description: 'Cooking in a shallow pan with oil' },
    ],
    station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
    difficulty: 'intermediate',
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    yield: 'Serves 4 as main course',
    ingredients: [
      { id: 'i1', name: 'Arborio Rice', weight: 300, unit: 'g', allergens: [], group: 'grain', sustainability: 'standard' },
      { id: 'i2', name: 'Porcini Mushrooms (dried)', weight: 20, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'seasonal' },
      { id: 'i3', name: 'White Wine', weight: 100, unit: 'ml', allergens: [], group: 'other', sustainability: 'standard' },
      { id: 'i4', name: 'Vegetable Stock', weight: 1000, unit: 'ml', allergens: [], group: 'other', sustainability: 'standard' },
      { id: 'i5', name: 'Butter', weight: 50, unit: 'g', allergens: ['milk'], group: 'dairy', sustainability: 'standard' },
      { id: 'i6', name: 'Parmigiano-Reggiano', weight: 80, unit: 'g', allergens: ['milk'], group: 'dairy', sustainability: 'standard' },
      { id: 'i7', name: 'Truffle Oil', weight: 5, unit: 'ml', allergens: [], group: 'oil', sustainability: 'standard' },
      { id: 'i8', name: 'Salt', weight: 5, unit: 'g', allergens: [], group: 'seasoning', sustainability: 'standard' },
      { id: 'i9', name: 'Black Pepper', weight: 2, unit: 'g', allergens: [], group: 'seasoning', sustainability: 'standard' },
    ],
    steps: [
      {
        id: 's1',
        order: 1,
        instruction: 'Rehydrate porcini mushrooms in hot water for 15 minutes. Reserve the soaking liquid.',
        techniques: [],
        station: null,
        duration: 15,
      },
      {
        id: 's2',
        order: 2,
        instruction: 'Heat vegetable stock with mushroom soaking liquid in a separate pot and keep warm.',
        techniques: [],
        station: null,
        duration: 5,
      },
      {
        id: 's3',
        order: 3,
        instruction: 'Heat olive oil in a large pan, add shallots and sauté until softened.',
        techniques: ['pan_frying'],
        station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
        duration: 3,
      },
      {
        id: 's4',
        order: 4,
        instruction: 'Add Arborio rice and toast for 2 minutes, stirring constantly.',
        techniques: ['pan_frying'],
        station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
        duration: 2,
      },
      {
        id: 's5',
        order: 5,
        instruction: 'Deglaze with white wine, stirring until absorbed.',
        techniques: [],
        station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
        duration: 2,
      },
      {
        id: 's6',
        order: 6,
        instruction: 'Add warm stock one ladle at a time, stirring frequently until rice is creamy and al dente.',
        techniques: ['simmering'],
        station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
        duration: 18,
      },
      {
        id: 's7',
        order: 7,
        instruction: 'Finish with butter, Parmigiano-Reggiano, and truffle oil. Season with salt and pepper.',
        techniques: [],
        station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
        duration: 2,
      },
    ],
    allergens: [
      { id: 'milk', name: 'Milk (including lactose)', code: 'milk' },
    ],
    foodCostPercent: 28,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=600&fit=crop',
    menuContext: ['a_la_carte', 'tasting_menu'],
    sustainability: {
      lowCarbon: true,
      seasonal: true,
      zeroWaste: false,
      score: 72,
    },
    rating: 4.8,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'recipe-2',
    title: 'Smørrebrød with Cured Fish',
    chef: MOCK_CHEFS[1],
    restaurant: 'Noma',
    description: 'Traditional Danish open-faced sandwich featuring house-cured Nordic fish on dense rye bread with seasonal vegetables.',
    cuisines: [
      { id: 'nordic', name: 'Nordic', parent: 'european' },
    ],
    techniques: [
      { id: 'curing', name: 'Curing', category: 'preservation', description: 'Preserving with salt and spices' },
    ],
    station: { id: 'garde_manger', name: 'Garde Manger', description: 'Cold station' },
    difficulty: 'intermediate',
    prepTime: 30,
    cookTime: 0,
    servings: 2,
    ingredients: [
      { id: 'i10', name: 'Rye Bread', weight: 200, unit: 'g', allergens: ['cereals'], group: 'grain', sustainability: 'local' },
      { id: 'i11', name: 'Fresh White Fish', weight: 300, unit: 'g', allergens: ['fish'], group: 'protein', sustainability: 'seasonal' },
      { id: 'i12', name: 'Sea Salt', weight: 10, unit: 'g', allergens: [], group: 'seasoning', sustainability: 'standard' },
      { id: 'i13', name: 'Dill', weight: 10, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'seasonal' },
      { id: 'i14', name: 'Beetroot', weight: 100, unit: 'g', allergens: [], group: 'vegetable', sustainability: 'seasonal' },
      { id: 'i15', name: 'Crème Fraîche', weight: 50, unit: 'g', allergens: ['milk'], group: 'dairy', sustainability: 'standard' },
    ],
    steps: [
      {
        id: 's8',
        order: 1,
        instruction: 'Cure white fish with sea salt and dill for 24 hours.',
        techniques: ['curing'],
        station: { id: 'garde_manger', name: 'Garde Manger', description: 'Cold station' },
        duration: 1440,
      },
      {
        id: 's9',
        order: 2,
        instruction: 'Roast beetroots until tender, then cut into thin slices.',
        techniques: [],
        station: null,
        duration: 45,
      },
      {
        id: 's10',
        order: 3,
        instruction: 'Slice rye bread and toast lightly.',
        techniques: ['roasting'],
        station: null,
        duration: 3,
      },
      {
        id: 's11',
        order: 4,
        instruction: 'Assemble: spread crème fraîche on bread, top with cured fish, beetroot, and fresh dill.',
        techniques: [],
        station: { id: 'garde_manger', name: 'Garde Manger', description: 'Cold station' },
        duration: 5,
      },
    ],
    allergens: [
      { id: 'cereals', name: 'Cereals containing gluten', code: 'gluten' },
      { id: 'fish', name: 'Fish', code: 'fish' },
      { id: 'milk', name: 'Milk (including lactose)', code: 'milk' },
    ],
    foodCostPercent: 35,
    image: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800&h=600&fit=crop',
    menuContext: ['a_la_carte', 'brunch'],
    sustainability: {
      lowCarbon: true,
      seasonal: true,
      zeroWaste: true,
      score: 88,
    },
    rating: 4.9,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'recipe-3',
    title: 'Saffron Risotto with Sea Urchin',
    chef: MOCK_CHEFS[2],
    restaurant: 'Gaggan',
    description: 'Elegant North Indian-influenced risotto with delicate saffron, finished with luxurious sea urchin roe.',
    cuisines: [
      { id: 'indian', name: 'Indian', parent: 'asian' },
      { id: 'indian_contemporary', name: 'Contemporary', parent: 'indian' },
    ],
    techniques: [
      { id: 'simmering', name: 'Simmering', category: 'wet_heat', description: 'Cooking in gently bubbling liquid' },
      { id: 'tempering', name: 'Tempering', category: 'pastry', description: 'Controlling chocolate crystallization' },
    ],
    station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
    difficulty: 'advanced',
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    ingredients: [
      { id: 'i16', name: 'Arborio Rice', weight: 280, unit: 'g', allergens: [], group: 'grain', sustainability: 'standard' },
      { id: 'i17', name: 'Saffron', weight: 0.5, unit: 'g', allergens: [], group: 'seasoning', sustainability: 'standard' },
      { id: 'i18', name: 'Sea Urchin Roe', weight: 80, unit: 'g', allergens: ['mollusks'], group: 'protein', sustainability: 'seasonal' },
      { id: 'i19', name: 'White Wine', weight: 100, unit: 'ml', allergens: [], group: 'other', sustainability: 'standard' },
      { id: 'i20', name: 'Fish Stock', weight: 1000, unit: 'ml', allergens: ['fish'], group: 'other', sustainability: 'standard' },
      { id: 'i21', name: 'Butter', weight: 60, unit: 'g', allergens: ['milk'], group: 'dairy', sustainability: 'standard' },
      { id: 'i22', name: 'Parmigiano-Reggiano', weight: 70, unit: 'g', allergens: ['milk'], group: 'dairy', sustainability: 'standard' },
    ],
    steps: [
      {
        id: 's12',
        order: 1,
        instruction: 'Steep saffron in warm fish stock for 10 minutes.',
        techniques: [],
        station: null,
        duration: 10,
      },
      {
        id: 's13',
        order: 2,
        instruction: 'Toast rice briefly in ghee with shallots.',
        techniques: ['pan_frying'],
        station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
        duration: 3,
      },
      {
        id: 's14',
        order: 3,
        instruction: 'Deglaze with white wine and allow to evaporate.',
        techniques: [],
        station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
        duration: 2,
      },
      {
        id: 's15',
        order: 4,
        instruction: 'Gradually add saffron-infused stock, stirring frequently until rice reaches perfect creaminess.',
        techniques: ['simmering'],
        station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
        duration: 18,
      },
      {
        id: 's16',
        order: 5,
        instruction: 'Finish with cold butter and Parmigiano, then top with sea urchin roe just before serving.',
        techniques: [],
        station: { id: 'entremetier', name: 'Entremetier', description: 'Vegetable station' },
        duration: 2,
      },
    ],
    allergens: [
      { id: 'mollusks', name: 'Mollusks', code: 'mollusks' },
      { id: 'fish', name: 'Fish', code: 'fish' },
      { id: 'milk', name: 'Milk (including lactose)', code: 'milk' },
    ],
    foodCostPercent: 42,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=600&fit=crop',
    menuContext: ['tasting_menu'],
    sustainability: {
      lowCarbon: false,
      seasonal: true,
      zeroWaste: false,
      score: 65,
    },
    rating: 4.7,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'recipe-4',
    title: 'Roasted Duck Breast with Cherry Gastrique',
    chef: MOCK_CHEFS[3],
    restaurant: 'The French Laundry',
    description: 'Perfect medium-rare duck breast with crispy skin, accompanied by a glossy cherry gastrique and seasonal vegetables.',
    cuisines: [
      { id: 'french', name: 'French', parent: 'european' },
      { id: 'french_classical', name: 'Classical', parent: 'french' },
    ],
    techniques: [
      { id: 'roasting', name: 'Roasting', category: 'dry_heat', description: 'Cooking with dry heat in an oven' },
      { id: 'searing', name: 'Searing', category: 'dry_heat', description: 'High-heat cooking to create crust' },
    ],
    station: { id: 'rotisseur', name: 'Rôtisseur', description: 'Roast station' },
    difficulty: 'advanced',
    prepTime: 20,
    cookTime: 30,
    servings: 4,
    ingredients: [
      { id: 'i23', name: 'Duck Breast', weight: 800, unit: 'g', allergens: [], group: 'protein', sustainability: 'standard' },
      { id: 'i24', name: 'Fresh Cherries', weight: 300, unit: 'g', allergens: [], group: 'fruit', sustainability: 'seasonal' },
      { id: 'i25', name: 'Red Wine Vinegar', weight: 50, unit: 'ml', allergens: [], group: 'other', sustainability: 'standard' },
      { id: 'i26', name: 'Sugar', weight: 50, unit: 'g', allergens: [], group: 'seasoning', sustainability: 'standard' },
      { id: 'i27', name: 'Duck Stock', weight: 200, unit: 'ml', allergens: [], group: 'other', sustainability: 'standard' },
      { id: 'i28', name: 'Thyme', weight: 5, unit: 'g', allergens: [], group: 'seasoning', sustainability: 'seasonal' },
      { id: 'i29', name: 'Sea Salt', weight: 5, unit: 'g', allergens: [], group: 'seasoning', sustainability: 'standard' },
    ],
    steps: [
      {
        id: 's17',
        order: 1,
        instruction: 'Score duck skin crosshatch pattern without cutting into flesh.',
        techniques: [],
        station: { id: 'rotisseur', name: 'Rôtisseur', description: 'Roast station' },
        duration: 5,
      },
      {
        id: 's18',
        order: 2,
        instruction: 'Season duck breasts with salt and pepper.',
        techniques: [],
        station: { id: 'rotisseur', name: 'Rôtisseur', description: 'Roast station' },
        duration: 2,
      },
      {
        id: 's19',
        order: 3,
        instruction: 'Sear skin-side down in cold pan, gradually increasing heat to render fat until skin is golden and crispy.',
        techniques: ['searing'],
        station: { id: 'rotisseur', name: 'Rôtisseur', description: 'Roast station' },
        duration: 10,
      },
      {
        id: 's20',
        order: 4,
        instruction: 'Flip and sear meat side briefly, then roast at 60°C until medium-rare.',
        techniques: ['roasting', 'searing'],
        station: { id: 'rotisseur', name: 'Rôtisseur', description: 'Roast station' },
        duration: 12,
      },
      {
        id: 's21',
        order: 5,
        instruction: 'Rest duck for 8 minutes while preparing gastrique.',
        techniques: [],
        station: null,
        duration: 8,
      },
      {
        id: 's22',
        order: 6,
        instruction: 'For gastrique: combine sugar and vinegar, caramelize sugar, add cherries and stock, reduce until glossy.',
        techniques: [],
        station: { id: 'saucier', name: 'Saucier', description: 'Sauce station' },
        duration: 8,
      },
    ],
    allergens: [],
    foodCostPercent: 38,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=600&fit=crop',
    menuContext: ['a_la_carte', 'tasting_menu'],
    sustainability: {
      lowCarbon: false,
      seasonal: true,
      zeroWaste: false,
      score: 58,
    },
    rating: 4.9,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'recipe-5',
    title: 'Oyster with Champagne Foam',
    chef: MOCK_CHEFS[4],
    restaurant: 'Core by Clare Smyth',
    description: 'Fresh British oyster topped with delicate champagne foam and caviar, a celebration of minimalism and precision.',
    cuisines: [
      { id: 'british', name: 'British', parent: 'european' },
    ],
    techniques: [
      { id: 'foaming', name: 'Foaming', category: 'modernist', description: 'Creating foams and airs' },
    ],
    station: { id: 'garde_manger', name: 'Garde Manger', description: 'Cold station' },
    difficulty: 'advanced',
    prepTime: 15,
    cookTime: 5,
    servings: 6,
    ingredients: [
      { id: 'i30', name: 'Fresh Oysters', weight: 150, unit: 'g', allergens: ['mollusks'], group: 'protein', sustainability: 'seasonal' },
      { id: 'i31', name: 'Champagne', weight: 100, unit: 'ml', allergens: [], group: 'other', sustainability: 'standard' },
      { id: 'i32', name: 'Lecithin', weight: 2, unit: 'g', allergens: ['soybeans'], group: 'other', sustainability: 'standard' },
      { id: 'i33', name: 'Caviar', weight: 20, unit: 'g', allergens: ['fish'], group: 'protein', sustainability: 'standard' },
      { id: 'i34', name: 'Salt', weight: 2, unit: 'g', allergens: [], group: 'seasoning', sustainability: 'standard' },
      { id: 'i35', name: 'Lemon', weight: 30, unit: 'g', allergens: [], group: 'fruit', sustainability: 'seasonal' },
    ],
    steps: [
      {
        id: 's23',
        order: 1,
        instruction: 'Shuck oysters carefully, keeping in their shells and ice-cold.',
        techniques: [],
        station: { id: 'garde_manger', name: 'Garde Manger', description: 'Cold station' },
        duration: 10,
      },
      {
        id: 's24',
        order: 2,
        instruction: 'Combine champagne with soy lecithin using an immersion blender to create stable foam.',
        techniques: ['foaming'],
        station: { id: 'garde_manger', name: 'Garde Manger', description: 'Cold station' },
        duration: 5,
      },
      {
        id: 's25',
        order: 3,
        instruction: 'Top each oyster with champagne foam and a pearl of caviar.',
        techniques: ['foaming'],
        station: { id: 'garde_manger', name: 'Garde Manger', description: 'Cold station' },
        duration: 2,
      },
      {
        id: 's26',
        order: 4,
        instruction: 'Garnish with microgreens and a squeeze of fresh lemon juice.',
        techniques: [],
        station: { id: 'garde_manger', name: 'Garde Manger', description: 'Cold station' },
        duration: 1,
      },
    ],
    allergens: [
      { id: 'mollusks', name: 'Mollusks', code: 'mollusks' },
      { id: 'fish', name: 'Fish', code: 'fish' },
      { id: 'soybeans', name: 'Soybeans', code: 'soybeans' },
    ],
    foodCostPercent: 45,
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&h=600&fit=crop',
    menuContext: ['tasting_menu'],
    sustainability: {
      lowCarbon: true,
      seasonal: true,
      zeroWaste: true,
      score: 82,
    },
    rating: 4.8,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

MOCK_RECIPES.forEach((recipe) => {
  const chef = MOCK_CHEFS.find((c) => c.id === recipe.chef.id);
  if (chef) {
    chef.recipes.push(recipe);
  }
});

export const MOCK_MASTERCLASSES: Masterclass[] = [
  {
    id: 'mc-1',
    title: 'Modern Italian Cooking Fundamentals',
    chef: MOCK_CHEFS[0],
    description: 'Master the techniques behind contemporary Italian cuisine with Massimo Bottura. Learn how tradition meets innovation.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop',
    level: 'intermediate',
    cuisine: ['Italian', 'Modern European'],
    duration: 180,
    price: 299,
    episodes: [
      {
        id: 'ep-1',
        order: 1,
        title: 'Introduction to Modernist Techniques',
        description: 'Explore the philosophy behind modern Italian cooking and essential modernist methods.',
        duration: 45,
        relatedRecipeIds: ['recipe-1'],
      },
      {
        id: 'ep-2',
        order: 2,
        title: 'Risotto Mastery',
        description: 'Perfect your risotto technique with detailed guidance on texture and flavor balance.',
        duration: 60,
        relatedRecipeIds: ['recipe-1'],
      },
      {
        id: 'ep-3',
        order: 3,
        title: 'Molecular Emulsions and Foams',
        description: 'Create stunning emulsions and foams to elevate your presentations.',
        duration: 75,
        relatedRecipeIds: [],
      },
    ],
    rating: 4.8,
    enrollmentCount: 1243,
    createdAt: new Date(),
  },
  {
    id: 'mc-2',
    title: 'Nordic Foraging and Sustainable Cooking',
    chef: MOCK_CHEFS[1],
    description: 'Join René Redzepi in exploring Nordic cuisine through foraging, seasonality, and sustainable practices.',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=600&fit=crop',
    level: 'advanced',
    cuisine: ['Nordic', 'Scandinavian'],
    duration: 240,
    price: 449,
    episodes: [
      {
        id: 'ep-4',
        order: 1,
        title: 'Foraging Essentials',
        description: 'Learn to identify and responsibly harvest wild ingredients for your kitchen.',
        duration: 60,
        relatedRecipeIds: ['recipe-2'],
      },
      {
        id: 'ep-5',
        order: 2,
        title: 'Seasonal Menu Planning',
        description: 'Structure menus around seasonal availability and optimize ingredient usage.',
        duration: 60,
        relatedRecipeIds: [],
      },
      {
        id: 'ep-6',
        order: 3,
        title: 'Zero Waste Cooking',
        description: 'Minimize waste through creative utilization of every ingredient component.',
        duration: 60,
        relatedRecipeIds: ['recipe-2'],
      },
      {
        id: 'ep-7',
        order: 4,
        title: 'Traditional Preservation Techniques',
        description: 'Master curing, fermentation, and drying to extend ingredient seasons.',
        duration: 60,
        relatedRecipeIds: [],
      },
    ],
    rating: 4.9,
    enrollmentCount: 2156,
    createdAt: new Date(),
  },
];

MOCK_CHEFS.forEach((chef) => {
  const masterclasses = MOCK_MASTERCLASSES.filter((mc) => mc.chef.id === chef.id);
  chef.masterclasses = masterclasses;
});

export const MOCK_JOBS: Job[] = [
  {
    id: 'job-1',
    title: 'Head Chef',
    restaurant: 'Fine Dining Restaurant Singapore',
    position: 'Head Chef',
    cuisine: ['French', 'Contemporary'],
    location: 'Singapore',
    salary: { min: 120000, max: 180000, currency: 'SGD' },
    description: 'We are seeking an experienced Head Chef to lead our kitchen team of 12 chefs.',
    requirements: [
      'Minimum 10 years executive kitchen experience',
      '3+ Michelin stars or equivalent accolades',
      'French classical training',
      'Team leadership experience',
    ],
    experienceLevel: 'executive',
    type: 'full_time',
    postedDate: new Date(),
    deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'job-2',
    title: 'Sous Chef - Pastry',
    restaurant: 'Artisan Bakery',
    position: 'Sous Chef - Pastry',
    cuisine: ['Pastry', 'Bakery'],
    location: 'Singapore',
    salary: { min: 60000, max: 80000, currency: 'SGD' },
    description: 'Join our pastry team as a Sous Chef. Create stunning desserts and bread products.',
    requirements: [
      'Pastry diploma or equivalent',
      '5+ years pastry experience',
      'Knowledge of lamination and tempering',
      'Production management experience',
    ],
    experienceLevel: 'mid',
    type: 'full_time',
    postedDate: new Date(),
  },
];

export const MOCK_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-1',
    name: 'Premium Seafood Wholesale',
    type: ['Fish', 'Shellfish', 'Seafood'],
    description: 'Premium wild-caught and responsibly farmed seafood sourced directly from sustainable fisheries.',
    location: 'Singapore',
    rating: 4.8,
    specialties: ['Wild-caught fish', 'Live lobster', 'Scallops', 'Oysters'],
    verified: true,
    website: 'https://example.com',
    createdAt: new Date(),
  },
  {
    id: 'sup-2',
    name: 'Organic Farm Collective',
    type: ['Vegetables', 'Fruits', 'Herbs'],
    description: 'Seasonal organic produce from local farms in the region, delivered fresh daily.',
    location: 'Singapore',
    rating: 4.7,
    specialties: ['Organic vegetables', 'Heirloom varieties', 'Microgreens', 'Edible flowers'],
    verified: true,
    website: 'https://example.com',
    createdAt: new Date(),
  },
  {
    id: 'sup-3',
    name: 'Heritage Grain Mill',
    type: ['Grains', 'Flour', 'Bread'],
    description: 'Artisanal grains and flours milled to order for the finest bakers and chefs.',
    location: 'Singapore',
    rating: 4.9,
    specialties: ['Heritage grains', 'Custom milling', 'Sourdough cultures', 'Specialty flours'],
    verified: true,
    createdAt: new Date(),
  },
];
