"""Top 200 professional chefs from around the world."""

from dataclasses import dataclass
from typing import Optional


@dataclass
class Chef:
    """Professional chef data."""

    id: str
    name: str
    restaurant: str
    location: str
    country: str
    tier: int  # 1, 2, or 3
    website: Optional[str] = None
    cuisine_tags: Optional[list[str]] = None
    accolades: Optional[list[str]] = None
    michelin_stars: int = 0
    world_rank: Optional[int] = None


# Tier 1: Global icons (Priority 1) - Chefs 1-50
TIER_1_CHEFS = [
    Chef(
        id="chef_001",
        name="Massimo Bottura",
        restaurant="Osteria Francescana",
        location="Modena",
        country="Italy",
        tier=1,
        website="https://www.osteriafrancescana.it",
        cuisine_tags=["Italian", "Modern"],
        accolades=["3 Michelin Stars", "1st World's 50 Best Restaurants 2016"],
        michelin_stars=3,
        world_rank=1,
    ),
    Chef(
        id="chef_002",
        name="Joan Rocafort",
        restaurant="El Celler de Can Roca",
        location="Girona",
        country="Spain",
        tier=1,
        website="https://www.cellercanroca.com",
        cuisine_tags=["Catalan", "Modern"],
        accolades=["3 Michelin Stars", "1st World's 50 Best Restaurants 2009"],
        michelin_stars=3,
        world_rank=2,
    ),
    Chef(
        id="chef_003",
        name="Alain Ducasse",
        restaurant="Alain Ducasse at The Dorchester",
        location="London",
        country="United Kingdom",
        tier=1,
        website="https://www.alainducasse.com",
        cuisine_tags=["French", "Classical"],
        accolades=["3 Michelin Stars", "Lifetime Achievement"],
        michelin_stars=3,
        world_rank=3,
    ),
    Chef(
        id="chef_004",
        name="Thomas Keller",
        restaurant="The French Laundry",
        location="Napa Valley",
        country="United States",
        tier=1,
        website="https://www.thefrenchlaundry.com",
        cuisine_tags=["French-American", "Haute Cuisine"],
        accolades=["3 Michelin Stars", "James Beard Award"],
        michelin_stars=3,
        world_rank=4,
    ),
    Chef(
        id="chef_005",
        name="Alice Waters",
        restaurant="Chez Panisse",
        location="Berkeley",
        country="United States",
        tier=1,
        website="https://www.chezpanisse.com",
        cuisine_tags=["California", "Farm-to-Table"],
        accolades=["James Beard Award", "Slow Food Pioneer"],
        michelin_stars=1,
        world_rank=5,
    ),
    Chef(
        id="chef_006",
        name="Wolfgang Puck",
        restaurant="Spago",
        location="Beverly Hills",
        country="United States",
        tier=1,
        website="https://www.wolfgangpuck.com",
        cuisine_tags=["Californian", "Fusion"],
        accolades=["James Beard Award", "Lifetime Achievement"],
        michelin_stars=2,
        world_rank=6,
    ),
    Chef(
        id="chef_007",
        name="Ferran Adrià",
        restaurant="El Bulli",
        location="Roses",
        country="Spain",
        tier=1,
        website="https://elbulli.com",
        cuisine_tags=["Molecular Gastronomy", "Spanish"],
        accolades=["3 Michelin Stars", "World's 50 Best Restaurant"],
        michelin_stars=3,
        world_rank=7,
    ),
    Chef(
        id="chef_008",
        name="Jacques Pépin",
        restaurant="Self-Employed Consultant",
        location="Connecticut",
        country="United States",
        tier=1,
        website="https://www.jacquespecin.com",
        cuisine_tags=["French", "Classical"],
        accolades=["James Beard Award", "TV Personality"],
        michelin_stars=0,
        world_rank=8,
    ),
    Chef(
        id="chef_009",
        name="Mario Batali",
        restaurant="Babbo",
        location="New York",
        country="United States",
        tier=1,
        website="https://www.batalirestaurants.com",
        cuisine_tags=["Italian", "Modern"],
        accolades=["James Beard Award", "TV Personality"],
        michelin_stars=1,
        world_rank=9,
    ),
    Chef(
        id="chef_010",
        name="Daniel Boulud",
        restaurant="Daniel",
        location="New York",
        country="United States",
        tier=1,
        website="https://www.danielnyc.com",
        cuisine_tags=["French", "Classical"],
        accolades=["3 Michelin Stars", "James Beard Award"],
        michelin_stars=2,
        world_rank=10,
    ),
    Chef(
        id="chef_011",
        name="Gordon Ramsay",
        restaurant="Restaurant Gordon Ramsay",
        location="London",
        country="United Kingdom",
        tier=1,
        website="https://www.gordonramsay.com",
        cuisine_tags=["French", "Modern British"],
        accolades=["3 Michelin Stars", "TV Personality"],
        michelin_stars=3,
        world_rank=11,
    ),
    Chef(
        id="chef_012",
        name="Joël Robuchon",
        restaurant="Joël Robuchon",
        location="Paris",
        country="France",
        tier=1,
        website="https://www.joelrobuchon.net",
        cuisine_tags=["French", "Haute Cuisine"],
        accolades=["3 Michelin Stars", "Lifetime Achievement"],
        michelin_stars=3,
        world_rank=12,
    ),
    Chef(
        id="chef_013",
        name="Thomas Haas",
        restaurant="Thomas Haas Chocolates",
        location="Vancouver",
        country="Canada",
        tier=1,
        website="https://www.thomashaas.com",
        cuisine_tags=["Pastry", "Chocolate"],
        accolades=["International Award Winner"],
        michelin_stars=0,
        world_rank=13,
    ),
    Chef(
        id="chef_014",
        name="Nobu Matsuhisa",
        restaurant="Nobu",
        location="Tokyo",
        country="Japan",
        tier=1,
        website="https://www.noburestaurants.com",
        cuisine_tags=["Japanese", "Peruvian Fusion"],
        accolades=["3 Michelin Stars", "James Beard Award"],
        michelin_stars=2,
        world_rank=14,
    ),
    Chef(
        id="chef_015",
        name="Emeril Lagasse",
        restaurant="Emeril's",
        location="New Orleans",
        country="United States",
        tier=1,
        website="https://www.emerils.com",
        cuisine_tags=["Creole", "Cajun"],
        accolades=["James Beard Award", "TV Personality"],
        michelin_stars=1,
        world_rank=15,
    ),
    Chef(
        id="chef_016",
        name="Auguste Escoffier",
        restaurant="Historical",
        location="France",
        country="France",
        tier=1,
        website=None,
        cuisine_tags=["French", "Classical"],
        accolades=["Founder of Modern Cuisine"],
        michelin_stars=0,
        world_rank=16,
    ),
    Chef(
        id="chef_017",
        name="Julia Child",
        restaurant="Self-Employed",
        location="Massachusetts",
        country="United States",
        tier=1,
        website=None,
        cuisine_tags=["French", "Educational"],
        accolades=["James Beard Award", "TV Pioneer"],
        michelin_stars=0,
        world_rank=17,
    ),
    Chef(
        id="chef_018",
        name="Jacques Torres",
        restaurant="Jacques Torres Chocolate",
        location="New York",
        country="United States",
        tier=1,
        website="https://www.jacquestorres.com",
        cuisine_tags=["Pastry", "Chocolate"],
        accolades=["Pastry Chef of the Year"],
        michelin_stars=0,
        world_rank=18,
    ),
    Chef(
        id="chef_019",
        name="Pierre Gagnaire",
        restaurant="Pierre Gagnaire",
        location="Paris",
        country="France",
        tier=1,
        website="https://www.pierre-gagnaire.com",
        cuisine_tags=["French", "Innovative"],
        accolades=["3 Michelin Stars"],
        michelin_stars=3,
        world_rank=19,
    ),
    Chef(
        id="chef_020",
        name="Dominique Crenn",
        restaurant="Atelier Crenn",
        location="San Francisco",
        country="United States",
        tier=1,
        website="https://www.ateliercrenn.com",
        cuisine_tags=["French", "Modern"],
        accolades=["3 Michelin Stars", "James Beard Award"],
        michelin_stars=3,
        world_rank=20,
    ),
    Chef(
        id="chef_021",
        name="Paul Bocuse",
        restaurant="L'Auberge du Pont de Collonges",
        location="Lyon",
        country="France",
        tier=1,
        website="https://www.bocuse.fr",
        cuisine_tags=["French", "Nouvelle Cuisine"],
        accolades=["3 Michelin Stars", "Lifetime Achievement"],
        michelin_stars=3,
        world_rank=21,
    ),
    Chef(
        id="chef_022",
        name="Charlie Trotter",
        restaurant="Charlie Trotter's",
        location="Chicago",
        country="United States",
        tier=1,
        website="https://www.charlietrotters.com",
        cuisine_tags=["Contemporary American", "New American"],
        accolades=["3 Michelin Stars", "James Beard Award"],
        michelin_stars=3,
        world_rank=22,
    ),
    Chef(
        id="chef_023",
        name="Heston Blumenthal",
        restaurant="The Fat Duck",
        location="Berkshire",
        country="United Kingdom",
        tier=1,
        website="https://www.thefatduck.co.uk",
        cuisine_tags=["Molecular Gastronomy", "British"],
        accolades=["3 Michelin Stars", "World's 50 Best Restaurant"],
        michelin_stars=3,
        world_rank=23,
    ),
    Chef(
        id="chef_024",
        name="Marco Pierre White",
        restaurant="Harvey's",
        location="London",
        country="United Kingdom",
        tier=1,
        website="https://www.marcpierrewhite.com",
        cuisine_tags=["French", "Modern British"],
        accolades=["3 Michelin Stars", "Television Personality"],
        michelin_stars=3,
        world_rank=24,
    ),
    Chef(
        id="chef_025",
        name="Juan Mari Arzak",
        restaurant="Arzak",
        location="San Sebastián",
        country="Spain",
        tier=1,
        website="https://www.arzak.es",
        cuisine_tags=["Basque", "Molecular"],
        accolades=["3 Michelin Stars", "World's Best Chef"],
        michelin_stars=3,
        world_rank=25,
    ),
    Chef(
        id="chef_026",
        name="Paul Prudhomme",
        restaurant="K Paul's",
        location="New Orleans",
        country="United States",
        tier=1,
        website="https://www.kpauls.com",
        cuisine_tags=["Creole", "Cajun"],
        accolades=["James Beard Award", "Chef of the Year"],
        michelin_stars=0,
        world_rank=26,
    ),
    Chef(
        id="chef_027",
        name="José Andrés",
        restaurant="Jaleo",
        location="Washington DC",
        country="United States",
        tier=1,
        website="https://www.joseandres.com",
        cuisine_tags=["Spanish", "Humanitarian"],
        accolades=["James Beard Award", "Philanthropist"],
        michelin_stars=0,
        world_rank=27,
    ),
    Chef(
        id="chef_028",
        name="Lidia Bastianich",
        restaurant="Lidia's",
        location="New York",
        country="United States",
        tier=1,
        website="https://www.lidiasitaly.com",
        cuisine_tags=["Italian", "Educational"],
        accolades=["James Beard Award", "TV Personality"],
        michelin_stars=1,
        world_rank=28,
    ),
    Chef(
        id="chef_029",
        name="Bobby Flay",
        restaurant="Gato",
        location="New York",
        country="United States",
        tier=1,
        website="https://www.bobbyflay.com",
        cuisine_tags=["Southwestern", "American"],
        accolades=["James Beard Award", "TV Personality"],
        michelin_stars=0,
        world_rank=29,
    ),
    Chef(
        id="chef_030",
        name="Ina Garten",
        restaurant="Self-Employed",
        location="Connecticut",
        country="United States",
        tier=1,
        website="https://www.barefoot contessa.com",
        cuisine_tags=["French", "Entertaining"],
        accolades=["TV Personality", "Cookbook Author"],
        michelin_stars=0,
        world_rank=30,
    ),
    Chef(
        id="chef_031",
        name="Wolfgang von Guerard",
        restaurant="L'Absinthe",
        location="Paris",
        country="France",
        tier=1,
        website="https://www.labsinthe.com",
        cuisine_tags=["French", "Classical"],
        accolades=["2 Michelin Stars"],
        michelin_stars=2,
        world_rank=31,
    ),
    Chef(
        id="chef_032",
        name="Martin Berasategui",
        restaurant="Martín Berasategui",
        location="San Sebastián",
        country="Spain",
        tier=1,
        website="https://www.martinberasategui.com",
        cuisine_tags=["Basque", "Modern"],
        accolades=["3 Michelin Stars"],
        michelin_stars=3,
        world_rank=32,
    ),
    Chef(
        id="chef_033",
        name="Andoni Luis Aduriz",
        restaurant="Alinea",
        location="Chicago",
        country="United States",
        tier=1,
        website="https://www.alinea.com",
        cuisine_tags=["Molecular Gastronomy", "Experimental"],
        accolades=["3 Michelin Stars", "World's 50 Best"],
        michelin_stars=3,
        world_rank=33,
    ),
    Chef(
        id="chef_034",
        name="Grant Achatz",
        restaurant="Alinea",
        location="Chicago",
        country="United States",
        tier=1,
        website="https://www.alinea.com",
        cuisine_tags=["Modern American", "Experimental"],
        accolades=["3 Michelin Stars", "James Beard Award"],
        michelin_stars=3,
        world_rank=34,
    ),
    Chef(
        id="chef_035",
        name="Emeril Jean Lagasse",
        restaurant="Emeril's",
        location="New Orleans",
        country="United States",
        tier=1,
        website="https://www.emerils.com",
        cuisine_tags=["Cajun", "Creole"],
        accolades=["James Beard Award", "Chef of the Year"],
        michelin_stars=0,
        world_rank=35,
    ),
    Chef(
        id="chef_036",
        name="Alice Medrich",
        restaurant="Self-Employed",
        location="California",
        country="United States",
        tier=1,
        website="https://www.alicemedrich.com",
        cuisine_tags=["Pastry", "Chocolate"],
        accolades=["James Beard Award"],
        michelin_stars=0,
        world_rank=36,
    ),
    Chef(
        id="chef_037",
        name="Sandra Lee",
        restaurant="Self-Employed",
        location="New York",
        country="United States",
        tier=1,
        website="https://www.sandralee.com",
        cuisine_tags=["American", "Semi-Homemade"],
        accolades=["TV Personality"],
        michelin_stars=0,
        world_rank=37,
    ),
    Chef(
        id="chef_038",
        name="Anya von Bremzen",
        restaurant="Self-Employed",
        location="New York",
        country="United States",
        tier=1,
        website="https://www.anyavonbremzen.com",
        cuisine_tags=["International", "Food Writer"],
        accolades=["James Beard Award"],
        michelin_stars=0,
        world_rank=38,
    ),
    Chef(
        id="chef_039",
        name="Roy Choi",
        restaurant="Kogi",
        location="Los Angeles",
        country="United States",
        tier=1,
        website="https://www.roychoi.com",
        cuisine_tags=["Korean", "Fusion"],
        accolades=["James Beard Award"],
        michelin_stars=0,
        world_rank=39,
    ),
    Chef(
        id="chef_040",
        name="David Chang",
        restaurant="Momofuku",
        location="New York",
        country="United States",
        tier=1,
        website="https://www.momofukunyc.com",
        cuisine_tags=["Asian Fusion", "Modern"],
        accolades=["James Beard Award", "World's 50 Best"],
        michelin_stars=1,
        world_rank=40,
    ),
    Chef(
        id="chef_041",
        name="Thomas Keller",
        restaurant="Per Se",
        location="New York",
        country="United States",
        tier=1,
        website="https://www.perseny.com",
        cuisine_tags=["French", "Contemporary"],
        accolades=["3 Michelin Stars", "James Beard Award"],
        michelin_stars=3,
        world_rank=41,
    ),
    Chef(
        id="chef_042",
        name="Rick Bayless",
        restaurant="Frontera Grill",
        location="Chicago",
        country="United States",
        tier=1,
        website="https://www.rickbayless.com",
        cuisine_tags=["Mexican", "Regional"],
        accolades=["James Beard Award", "TV Personality"],
        michelin_stars=0,
        world_rank=42,
    ),
    Chef(
        id="chef_043",
        name="Bobby Flay",
        restaurant="Gato",
        location="New York",
        country="United States",
        tier=1,
        website="https://www.bobbyflay.com",
        cuisine_tags=["Southwestern", "Grilling"],
        accolades=["James Beard Award", "TV Personality"],
        michelin_stars=0,
        world_rank=43,
    ),
    Chef(
        id="chef_044",
        name="Emerald Isley",
        restaurant="Self-Employed",
        location="Georgia",
        country="United States",
        tier=1,
        website="https://www.emeraldisley.com",
        cuisine_tags=["Southern", "Contemporary"],
        accolades=["Food Writer"],
        michelin_stars=0,
        world_rank=44,
    ),
    Chef(
        id="chef_045",
        name="Susie Orman",
        restaurant="Self-Employed",
        location="California",
        country="United States",
        tier=1,
        website="https://www.susieorman.com",
        cuisine_tags=["International", "Educator"],
        accolades=["Food Writer"],
        michelin_stars=0,
        world_rank=45,
    ),
    Chef(
        id="chef_046",
        name="Tyler Florence",
        restaurant="Wayfare Tavern",
        location="San Francisco",
        country="United States",
        tier=1,
        website="https://www.tylerflorence.com",
        cuisine_tags=["American", "Contemporary"],
        accolades=["James Beard Award", "TV Personality"],
        michelin_stars=0,
        world_rank=46,
    ),
    Chef(
        id="chef_047",
        name="Guy Fieri",
        restaurant="Guy's American Kitchen",
        location="New York",
        country="United States",
        tier=1,
        website="https://www.guyfieri.com",
        cuisine_tags=["American", "Casual"],
        accolades=["TV Personality"],
        michelin_stars=0,
        world_rank=47,
    ),
    Chef(
        id="chef_048",
        name="Geoffrey Zakarian",
        restaurant="The Lambs Club",
        location="New York",
        country="United States",
        tier=1,
        website="https://www.geoffreyzakarian.com",
        cuisine_tags=["American", "Contemporary"],
        accolades=["James Beard Award", "TV Personality"],
        michelin_stars=1,
        world_rank=48,
    ),
    Chef(
        id="chef_049",
        name="Cat Cora",
        restaurant="Cat Cora's Taverna",
        location="San Francisco",
        country="United States",
        tier=1,
        website="https://www.catcora.com",
        cuisine_tags=["Mediterranean", "Greek"],
        accolades=["James Beard Award", "TV Personality"],
        michelin_stars=0,
        world_rank=49,
    ),
    Chef(
        id="chef_050",
        name="Danny Meyer",
        restaurant="Union Square Cafe",
        location="New York",
        country="United States",
        tier=1,
        website="https://www.unionhosp.com",
        cuisine_tags=["American", "Contemporary"],
        accolades=["James Beard Award", "Restaurant Founder"],
        michelin_stars=1,
        world_rank=50,
    ),
]

# Tier 2: Major culinary figures (Priority 2) - Chefs 51-120
TIER_2_CHEFS = [
    Chef(
        id="chef_051",
        name="Anne-Sophie Pic",
        restaurant="Maison Pic",
        location="Valence",
        country="France",
        tier=2,
        website="https://www.maison-pic.com",
        cuisine_tags=["French", "Modern"],
        accolades=["3 Michelin Stars"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_052",
        name="Carme Ruscalleda",
        restaurant="Sant Pau",
        location="Barcelona",
        country="Spain",
        tier=2,
        website="https://www.santpaurestaurant.com",
        cuisine_tags=["Catalan", "Innovative"],
        accolades=["3 Michelin Stars"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_053",
        name="Frank Gehry",
        restaurant="Dining Concepts",
        location="Los Angeles",
        country="United States",
        tier=2,
        website=None,
        cuisine_tags=["Design", "Architecture"],
        accolades=["Pritzker Prize"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_054",
        name="Michael Mina",
        restaurant="Michael Mina",
        location="San Francisco",
        country="United States",
        tier=2,
        website="https://www.michaelmina.net",
        cuisine_tags=["Seafood", "American"],
        accolades=["James Beard Award"],
        michelin_stars=2,
    ),
    Chef(
        id="chef_055",
        name="Wolfgang Puck",
        restaurant="Spago",
        location="Beverly Hills",
        country="United States",
        tier=2,
        website="https://www.wolfgangpuck.com",
        cuisine_tags=["Californian", "Fusion"],
        accolades=["James Beard Award", "Lifetime Achievement"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_056",
        name="José Ramón Castillo",
        restaurant="Punto MX",
        location="Mexico City",
        country="Mexico",
        tier=2,
        website="https://www.puntomx.com",
        cuisine_tags=["Mexican", "Modern"],
        accolades=["James Beard Award", "World's 50 Best"],
        michelin_stars=2,
    ),
    Chef(
        id="chef_057",
        name="Naomi Pomeroy",
        restaurant="Beast",
        location="Portland",
        country="United States",
        tier=2,
        website="https://www.beastpdx.com",
        cuisine_tags=["American", "Contemporary"],
        accolades=["James Beard Award"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_058",
        name="Stephanie Izard",
        restaurant="Girl & the Goat",
        location="Chicago",
        country="United States",
        tier=2,
        website="https://www.girlandthegoat.com",
        cuisine_tags=["American", "Contemporary"],
        accolades=["James Beard Award", "World's 50 Best"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_059",
        name="Kyle Connaughton",
        restaurant="The Macadamia",
        location="San Francisco",
        country="United States",
        tier=2,
        website="https://www.singrestaurant.com",
        cuisine_tags=["American", "Innovative"],
        accolades=["James Beard Award", "World's 50 Best"],
        michelin_stars=2,
    ),
    Chef(
        id="chef_060",
        name="Amanda Cohen",
        restaurant="Dirt Candy",
        location="New York",
        country="United States",
        tier=2,
        website="https://www.dirtcandynyc.com",
        cuisine_tags=["Vegetarian", "Contemporary"],
        accolades=["James Beard Award"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_061",
        name="Elena Arzak",
        restaurant="Arzak",
        location="San Sebastián",
        country="Spain",
        tier=2,
        website="https://www.arzak.es",
        cuisine_tags=["Basque", "Innovative"],
        accolades=["3 Michelin Stars"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_062",
        name="Corey Lee",
        restaurant="Benu",
        location="San Francisco",
        country="United States",
        tier=2,
        website="https://www.benusf.com",
        cuisine_tags=["American", "Contemporary"],
        accolades=["James Beard Award", "World's 50 Best"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_063",
        name="Richard Blais",
        restaurant="Trail Blais",
        location="Atlanta",
        country="United States",
        tier=2,
        website="https://www.richardblais.net",
        cuisine_tags=["American", "Innovative"],
        accolades=["James Beard Award", "TV Personality"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_064",
        name="Michael Voltaggio",
        restaurant="Ink",
        location="Los Angeles",
        country="United States",
        tier=2,
        website="https://www.voltaggio.com",
        cuisine_tags=["American", "Contemporary"],
        accolades=["James Beard Award", "TV Personality"],
        michelin_stars=2,
    ),
    Chef(
        id="chef_065",
        name="Bryan Voltaggio",
        restaurant="Volt",
        location="Frederick",
        country="United States",
        tier=2,
        website="https://www.voltrestaurant.com",
        cuisine_tags=["American", "Contemporary"],
        accolades=["James Beard Award", "TV Personality"],
        michelin_stars=2,
    ),
    Chef(
        id="chef_066",
        name="Spike Mendelsohn",
        restaurant="Good Stuff Eatery",
        location="Washington DC",
        country="United States",
        tier=2,
        website="https://www.spikemendelsohn.com",
        cuisine_tags=["American", "Casual"],
        accolades=["TV Personality"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_067",
        name="Fabio Viviani",
        restaurant="Cafe Firenze",
        location="Los Angeles",
        country="United States",
        tier=2,
        website="https://www.fabiocooking.com",
        cuisine_tags=["Italian", "Contemporary"],
        accolades=["TV Personality"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_068",
        name="Curtis Stone",
        restaurant="Maude",
        location="Los Angeles",
        country="United States",
        tier=2,
        website="https://www.curtisstone.com",
        cuisine_tags=["Modern European", "Contemporary"],
        accolades=["James Beard Award", "TV Personality"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_069",
        name="Giada De Laurentiis",
        restaurant="Giada",
        location="Las Vegas",
        country="United States",
        tier=2,
        website="https://www.giadalaurentis.com",
        cuisine_tags=["Italian", "Casual"],
        accolades=["TV Personality"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_070",
        name="Nigella Lawson",
        restaurant="Self-Employed",
        location="London",
        country="United Kingdom",
        tier=2,
        website="https://www.nigella.com",
        cuisine_tags=["British", "Casual"],
        accolades=["TV Personality", "Cookbook Author"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_071",
        name="Jamie Oliver",
        restaurant="Jamie's Italian",
        location="London",
        country="United Kingdom",
        tier=2,
        website="https://www.jamieoliver.com",
        cuisine_tags=["British", "Casual"],
        accolades=["James Beard Award", "TV Personality"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_072",
        name="Delia Smith",
        restaurant="Self-Employed",
        location="Norfolk",
        country="United Kingdom",
        tier=2,
        website="https://www.deliasmith.com",
        cuisine_tags=["British", "Educational"],
        accolades=["TV Personality", "Cookbook Author"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_073",
        name="Mary Berry",
        restaurant="Self-Employed",
        location="England",
        country="United Kingdom",
        tier=2,
        website="https://www.maryberry.com",
        cuisine_tags=["Pastry", "Baking"],
        accolades=["TV Personality", "Cookbook Author"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_074",
        name="Paul Hollywood",
        restaurant="Paul Hollywood Artisan Bakery",
        location="London",
        country="United Kingdom",
        tier=2,
        website="https://www.paulhollywood.com",
        cuisine_tags=["Baking", "Bread"],
        accolades=["TV Personality"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_075",
        name="Marco Pierre White",
        restaurant="Various",
        location="London",
        country="United Kingdom",
        tier=2,
        website="https://www.marcpierrewhite.com",
        cuisine_tags=["French", "Modern British"],
        accolades=["3 Michelin Stars", "TV Personality"],
        michelin_stars=2,
    ),
    Chef(
        id="chef_076",
        name="Rick Stein",
        restaurant="Rick Stein",
        location="Padstow",
        country="United Kingdom",
        tier=2,
        website="https://www.rickstein.com",
        cuisine_tags=["Seafood", "British"],
        accolades=["TV Personality", "Cookbook Author"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_077",
        name="Antony Worrall Thompson",
        restaurant="Grenadier",
        location="London",
        country="United Kingdom",
        tier=2,
        website="https://www.antonywt.com",
        cuisine_tags=["British", "Contemporary"],
        accolades=["TV Personality"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_078",
        name="Ainsley Harriott",
        restaurant="Various",
        location="London",
        country="United Kingdom",
        tier=2,
        website="https://www.ainsleyharriot.com",
        cuisine_tags=["Caribbean", "British"],
        accolades=["TV Personality"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_079",
        name="Mary Quant",
        restaurant="Self-Employed",
        location="London",
        country="United Kingdom",
        tier=2,
        website=None,
        cuisine_tags=["Design", "Fashion"],
        accolades=["Design Pioneer"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_080",
        name="Yotam Ottolenghi",
        restaurant="Ottolenghi",
        location="London",
        country="United Kingdom",
        tier=2,
        website="https://www.ottolenghi.co.uk",
        cuisine_tags=["Mediterranean", "Contemporary"],
        accolades=["Cookbook Author", "Food Writer"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_081",
        name="Samin Nosrat",
        restaurant="Self-Employed",
        location="San Francisco",
        country="United States",
        tier=2,
        website="https://www.saminnosrat.com",
        cuisine_tags=["Educational", "Contemporary"],
        accolades=["James Beard Award", "Food Writer"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_082",
        name="Diana Kennedy",
        restaurant="Self-Employed",
        location="Mexico",
        country="Mexico",
        tier=2,
        website="https://www.dianakennedy.com",
        cuisine_tags=["Mexican", "Traditional"],
        accolades=["James Beard Award", "Food Writer"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_083",
        name="Madhur Jaffrey",
        restaurant="Self-Employed",
        location="New York",
        country="United States",
        tier=2,
        website="https://www.madhurkitchen.com",
        cuisine_tags=["Indian", "International"],
        accolades=["James Beard Award", "TV Personality"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_084",
        name="Roy Choi",
        restaurant="Various",
        location="Los Angeles",
        country="United States",
        tier=2,
        website="https://www.roychoi.com",
        cuisine_tags=["Korean", "Fusion"],
        accolades=["James Beard Award", "Food Writer"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_085",
        name="Chad Robertson",
        restaurant="Tartine Bakery",
        location="San Francisco",
        country="United States",
        tier=2,
        website="https://www.tartinebakery.com",
        cuisine_tags=["Bread", "Baking"],
        accolades=["James Beard Award"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_086",
        name="Daniel Humm",
        restaurant="Eleven Madison Park",
        location="New York",
        country="United States",
        tier=2,
        website="https://www.elevenmadisonpark.com",
        cuisine_tags=["Contemporary American", "Innovative"],
        accolades=["3 Michelin Stars", "World's 50 Best"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_087",
        name="Petter Nilsson",
        restaurant="Noma",
        location="Copenhagen",
        country="Denmark",
        tier=2,
        website="https://www.noma.dk",
        cuisine_tags=["Nordic", "Innovative"],
        accolades=["3 Michelin Stars", "World's 50 Best"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_088",
        name="Alain Passard",
        restaurant="L'Arpège",
        location="Paris",
        country="France",
        tier=2,
        website="https://www.alain-passard.com",
        cuisine_tags=["French", "Vegetable-Based"],
        accolades=["3 Michelin Stars"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_089",
        name="Georges Blanc",
        restaurant="Georges Blanc",
        location="Vonnas",
        country="France",
        tier=2,
        website="https://www.georgesblanc.com",
        cuisine_tags=["French", "Classical"],
        accolades=["3 Michelin Stars"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_090",
        name="Guy Savoy",
        restaurant="Guy Savoy",
        location="Paris",
        country="France",
        tier=2,
        website="https://www.guysavoy.com",
        cuisine_tags=["French", "Innovative"],
        accolades=["3 Michelin Stars"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_091",
        name="Michel Guérard",
        restaurant="Les Prés d'Eugénie",
        location="Eugénie-les-Bains",
        country="France",
        tier=2,
        website="https://www.michelpresdeugenie.com",
        cuisine_tags=["French", "Nouvelle Cuisine"],
        accolades=["3 Michelin Stars"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_092",
        name="Joël Tillinac",
        restaurant="Joël Robuchon",
        location="Las Vegas",
        country="United States",
        tier=2,
        website="https://www.joelrobuchon.com",
        cuisine_tags=["French", "Modern"],
        accolades=["James Beard Award"],
        michelin_stars=2,
    ),
    Chef(
        id="chef_093",
        name="Albert Roux",
        restaurant="Gavroche",
        location="London",
        country="United Kingdom",
        tier=2,
        website="https://www.albertroux.com",
        cuisine_tags=["French", "Classical"],
        accolades=["3 Michelin Stars", "Lifetime Achievement"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_094",
        name="Michel Roux Jr.",
        restaurant="Le Gavroche",
        location="London",
        country="United Kingdom",
        tier=2,
        website="https://www.legavroche.com",
        cuisine_tags=["French", "Classical"],
        accolades=["2 Michelin Stars", "Lifetime Achievement"],
        michelin_stars=2,
    ),
    Chef(
        id="chef_095",
        name="Jeremiah Tower",
        restaurant="Stars",
        location="San Francisco",
        country="United States",
        tier=2,
        website="https://www.jeremiahhtower.com",
        cuisine_tags=["California", "Modern"],
        accolades=["James Beard Award", "Pioneer"],
        michelin_stars=2,
    ),
    Chef(
        id="chef_096",
        name="Mark Miller",
        restaurant="Coyote Cafe",
        location="Santa Fe",
        country="United States",
        tier=2,
        website="https://www.markmiller.com",
        cuisine_tags=["Southwestern", "Regional"],
        accolades=["James Beard Award"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_097",
        name="Dean Ornish",
        restaurant="Self-Employed",
        location="California",
        country="United States",
        tier=2,
        website="https://www.deanornish.com",
        cuisine_tags=["Heart-Healthy", "Vegetarian"],
        accolades=["Health Pioneer"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_098",
        name="David Kinch",
        restaurant="Manresa",
        location="Los Gatos",
        country="United States",
        tier=2,
        website="https://www.manresarestaurant.com",
        cuisine_tags=["California", "Contemporary"],
        accolades=["3 Michelin Stars", "World's 50 Best"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_099",
        name="Christopher Kostow",
        restaurant="The Restaurant at Meadowood",
        location="Napa Valley",
        country="United States",
        tier=2,
        website="https://www.themeadowood.com",
        cuisine_tags=["California", "Contemporary"],
        accolades=["3 Michelin Stars", "World's 50 Best"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_100",
        name="Thomas Keller",
        restaurant="Ad Hoc",
        location="Yountville",
        country="United States",
        tier=2,
        website="https://www.adhocrestaurant.com",
        cuisine_tags=["California", "Casual"],
        accolades=["James Beard Award"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_101",
        name="Alice Feiring",
        restaurant="Self-Employed",
        location="New York",
        country="United States",
        tier=2,
        website="https://www.alicefeiring.com",
        cuisine_tags=["Wine", "Natural Wine"],
        accolades=["Food Writer", "Wine Expert"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_102",
        name="Dan Barber",
        restaurant="Blue Hill",
        location="New York",
        country="United States",
        tier=2,
        website="https://www.bluehillfarm.com",
        cuisine_tags=["Farm-to-Table", "Contemporary"],
        accolades=["3 Michelin Stars", "World's 50 Best"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_103",
        name="Mugaritz",
        restaurant="Mugaritz",
        location="Errenteria",
        country="Spain",
        tier=2,
        website="https://www.mugaritz.com",
        cuisine_tags=["Innovative", "Molecular"],
        accolades=["2 Michelin Stars", "World's 50 Best"],
        michelin_stars=2,
    ),
    Chef(
        id="chef_104",
        name="Albert Adrià",
        restaurant="Tickets Bar",
        location="Barcelona",
        country="Spain",
        tier=2,
        website="https://www.ticketsbar.es",
        cuisine_tags=["Molecular Gastronomy", "Tapas"],
        accolades=["Michelin Star", "World's 50 Best"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_105",
        name="Yoji Tokuyoshi",
        restaurant="Kanda",
        location="Tokyo",
        country="Japan",
        tier=2,
        website="https://www.kanda-tokyo.com",
        cuisine_tags=["Japanese", "Modern"],
        accolades=["3 Michelin Stars"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_106",
        name="Hideki Hiwatashi",
        restaurant="Hideki",
        location="Tokyo",
        country="Japan",
        tier=2,
        website="https://www.hideki-tokyo.com",
        cuisine_tags=["Japanese", "Innovative"],
        accolades=["2 Michelin Stars"],
        michelin_stars=2,
    ),
    Chef(
        id="chef_107",
        name="Chang Nils Jäger",
        restaurant="Nisi Bon",
        location="Berlin",
        country="Germany",
        tier=2,
        website="https://www.nisibon.com",
        cuisine_tags=["German", "Contemporary"],
        accolades=["1 Michelin Star"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_108",
        name="Massimo Recchioni",
        restaurant="Recchioni",
        location="San Marino",
        country="San Marino",
        tier=2,
        website="https://www.recchioni.sm",
        cuisine_tags=["Italian", "Modern"],
        accolades=["1 Michelin Star"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_109",
        name="Alberto Gipponi",
        restaurant="Casa Crespo",
        location="Lima",
        country="Peru",
        tier=2,
        website="https://www.casacrespo.pe",
        cuisine_tags=["Peruvian", "Contemporary"],
        accolades=["World's 50 Best"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_110",
        name="Rafael Nadal",
        restaurant="Nadal Culinary",
        location="Mallorca",
        country="Spain",
        tier=2,
        website=None,
        cuisine_tags=["Spanish", "Mediterranean"],
        accolades=["Food Passion Project"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_111",
        name="Jordi Vilà",
        restaurant="Tickets Bar",
        location="Barcelona",
        country="Spain",
        tier=2,
        website="https://www.ticketsbar.es",
        cuisine_tags=["Spanish", "Tapas"],
        accolades=["World's 50 Best"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_112",
        name="Sergi Arola",
        restaurant="Sergi Arola Gastro",
        location="Madrid",
        country="Spain",
        tier=2,
        website="https://www.sergiarola.es",
        cuisine_tags=["Spanish", "Contemporary"],
        accolades=["2 Michelin Stars"],
        michelin_stars=2,
    ),
    Chef(
        id="chef_113",
        name="Paul Cunningham",
        restaurant="Restaurant Patrick Guilbaud",
        location="Dublin",
        country="Ireland",
        tier=2,
        website="https://www.patrickguilbaud.ie",
        cuisine_tags=["Irish", "Contemporary"],
        accolades=["2 Michelin Stars"],
        michelin_stars=2,
    ),
    Chef(
        id="chef_114",
        name="Nuno Mendes",
        restaurant="Taberna da Rua",
        location="Lisbon",
        country="Portugal",
        tier=2,
        website="https://www.tabelarua.pt",
        cuisine_tags=["Portuguese", "Contemporary"],
        accolades=["1 Michelin Star", "World's 50 Best"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_115",
        name="Aida Mollenkamp",
        restaurant="Self-Employed",
        location="California",
        country="United States",
        tier=2,
        website="https://www.aidamollenkamp.com",
        cuisine_tags=["Food Writer", "Television"],
        accolades=["Culinary Educator"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_116",
        name="Alex Atala",
        restaurant="D.O.M.",
        location="São Paulo",
        country="Brazil",
        tier=2,
        website="https://www.domrestaurant.com.br",
        cuisine_tags=["Brazilian", "Amazon"],
        accolades=["3 Michelin Stars", "World's 50 Best"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_117",
        name="Virgilio Martinez",
        restaurant="Central",
        location="Lima",
        country="Peru",
        tier=2,
        website="https://www.centralrestaurante.com.pe",
        cuisine_tags=["Peruvian", "Contemporary"],
        accolades=["3 Michelin Stars", "World's 50 Best"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_118",
        name="Enrique Olvera",
        restaurant="Pujol",
        location="Mexico City",
        country="Mexico",
        tier=2,
        website="https://www.pujolmexico.com",
        cuisine_tags=["Mexican", "Contemporary"],
        accolades=["3 Michelin Stars", "World's 50 Best"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_119",
        name="Chang Enrique",
        restaurant="Maido",
        location="Lima",
        country="Peru",
        tier=2,
        website="https://www.maidolima.com",
        cuisine_tags=["Peruvian-Japanese", "Fusion"],
        accolades=["2 Michelin Stars", "World's 50 Best"],
        michelin_stars=2,
    ),
    Chef(
        id="chef_120",
        name="Rene Redzepi",
        restaurant="Noma",
        location="Copenhagen",
        country="Denmark",
        tier=2,
        website="https://www.noma.dk",
        cuisine_tags=["Nordic", "Innovative"],
        accolades=["3 Michelin Stars", "World's 50 Best"],
        michelin_stars=3,
    ),
]

# Tier 3: Rising stars and regional leaders (Priority 3) - Chefs 121-200
TIER_3_CHEFS = [
    Chef(
        id="chef_121",
        name="Tetsuya Wakuda",
        restaurant="Tetsuya's",
        location="Sydney",
        country="Australia",
        tier=3,
        website="https://www.tetsuyas.com",
        cuisine_tags=["Australian", "French-Japanese"],
        accolades=["2 Michelin Stars"],
        michelin_stars=2,
    ),
    Chef(
        id="chef_122",
        name="Quentin Baille",
        restaurant="Thirteen Coins",
        location="Seattle",
        country="United States",
        tier=3,
        website="https://www.thirteencoins.com",
        cuisine_tags=["Pacific Northwest", "Contemporary"],
        accolades=["1 Michelin Star"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_123",
        name="Emeril Lagasse",
        restaurant="Emeril's Table",
        location="New Orleans",
        country="United States",
        tier=3,
        website="https://www.emerilstable.com",
        cuisine_tags=["Creole", "Casual"],
        accolades=["Food Network"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_124",
        name="Traci Des Jardins",
        restaurant="Jardinière",
        location="San Francisco",
        country="United States",
        tier=3,
        website="https://www.jardiniere.com",
        cuisine_tags=["California", "Contemporary"],
        accolades=["James Beard Award", "1 Michelin Star"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_125",
        name="Nancy Silverton",
        restaurant="Osteria Mozza",
        location="Los Angeles",
        country="United States",
        tier=3,
        website="https://www.osteriamoozza.com",
        cuisine_tags=["Italian", "Pastry"],
        accolades=["James Beard Award"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_126",
        name="Tom Collicchio",
        restaurant="Craft",
        location="New York",
        country="United States",
        tier=3,
        website="https://www.craftrestaurant.com",
        cuisine_tags=["American", "Contemporary"],
        accolades=["James Beard Award", "TV Personality"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_127",
        name="Gail Simmons",
        restaurant="Self-Employed",
        location="New York",
        country="United States",
        tier=3,
        website="https://www.gailsimmons.com",
        cuisine_tags=["Food Writer", "Media"],
        accolades=["Food & Wine Magazine"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_128",
        name="Padma Lakshmi",
        restaurant="Self-Employed",
        location="New York",
        country="United States",
        tier=3,
        website="https://www.padmalakshmi.com",
        cuisine_tags=["Indian", "Television"],
        accolades=["TV Personality", "Author"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_129",
        name="Wolfgang Hanau",
        restaurant="Hanau Culinary",
        location="Frankfurt",
        country="Germany",
        tier=3,
        website="https://www.hanaiculinary.de",
        cuisine_tags=["German", "Contemporary"],
        accolades=["1 Michelin Star"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_130",
        name="Massimo Montanari",
        restaurant="Self-Employed",
        location="Bologna",
        country="Italy",
        tier=3,
        website="https://www.massimomontanari.it",
        cuisine_tags=["Food History", "Academic"],
        accolades=["Food Historian"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_131",
        name="Ottavio Allemano",
        restaurant="Nuovo Cambio",
        location="Turin",
        country="Italy",
        tier=3,
        website="https://www.nuovocambio.it",
        cuisine_tags=["Italian", "Piemontese"],
        accolades=["1 Michelin Star"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_132",
        name="Marco Galtarossa",
        restaurant="Grappolo",
        location="Verona",
        country="Italy",
        tier=3,
        website="https://www.grappolo.com",
        cuisine_tags=["Italian", "Regional"],
        accolades=["1 Michelin Star"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_133",
        name="Andrea Berton",
        restaurant="Berton",
        location="Milan",
        country="Italy",
        tier=3,
        website="https://www.bertonmilano.com",
        cuisine_tags=["Italian", "Contemporary"],
        accolades=["2 Michelin Stars"],
        michelin_stars=2,
    ),
    Chef(
        id="chef_134",
        name="Niko Romito",
        restaurant="Reale",
        location="Abruzzo",
        country="Italy",
        tier=3,
        website="https://www.realerestaurant.com",
        cuisine_tags=["Italian", "Contemporary"],
        accolades=["3 Michelin Stars"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_135",
        name="Massimiliano Mascia",
        restaurant="Cézanne",
        location="Istanbul",
        country="Turkey",
        tier=3,
        website="https://www.cezanne-istanbul.com",
        cuisine_tags=["Turkish", "Contemporary"],
        accolades=["1 Michelin Star"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_136",
        name="Ayşe Öner",
        restaurant="Müzedechanga",
        location="Istanbul",
        country="Turkey",
        tier=3,
        website="https://www.muzedechanga.com",
        cuisine_tags=["Turkish", "Mediterranean"],
        accolades=["1 Michelin Star"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_137",
        name="Antonis Botrini",
        restaurant="Varoulko Seaside",
        location="Athens",
        country="Greece",
        tier=3,
        website="https://www.varoulko.gr",
        cuisine_tags=["Greek", "Seafood"],
        accolades=["2 Michelin Stars"],
        michelin_stars=2,
    ),
    Chef(
        id="chef_138",
        name="Costas Spiliadis",
        restaurant="Milos",
        location="Montreal",
        country="Canada",
        tier=3,
        website="https://www.milos.ca",
        cuisine_tags=["Greek", "Seafood"],
        accolades=["James Beard Award"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_139",
        name="David Zilber",
        restaurant="Alo",
        location="Toronto",
        country="Canada",
        tier=3,
        website="https://www.alorestaurant.com",
        cuisine_tags=["Canadian", "Contemporary"],
        accolades=["3 Michelin Stars", "World's 50 Best"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_140",
        name="Norman Musa",
        restaurant="Norman's at The Ritz-Carlton",
        location="Kuala Lumpur",
        country="Malaysia",
        tier=3,
        website="https://www.normanmusa.com",
        cuisine_tags=["Malaysian", "Contemporary"],
        accolades=["1 Michelin Star"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_141",
        name="Sun Teck Gan",
        restaurant="Restaurant Petaling Jaya",
        location="Kuala Lumpur",
        country="Malaysia",
        tier=3,
        website="https://www.sunteckgan.com",
        cuisine_tags=["Malaysian", "Traditional"],
        accolades=["Regional Award"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_142",
        name="Akira Oshima",
        restaurant="Oshima",
        location="Singapore",
        country="Singapore",
        tier=3,
        website="https://www.oshibmtokyo.sg",
        cuisine_tags=["Japanese", "Contemporary"],
        accolades=["2 Michelin Stars"],
        michelin_stars=2,
    ),
    Chef(
        id="chef_143",
        name="Jason Atherton",
        restaurant="Pollen Street Social",
        location="London",
        country="United Kingdom",
        tier=3,
        website="https://www.pollenstreetsocial.com",
        cuisine_tags=["British", "Contemporary"],
        accolades=["2 Michelin Stars"],
        michelin_stars=2,
    ),
    Chef(
        id="chef_144",
        name="Angela Hartnett",
        restaurant="Murano",
        location="London",
        country="United Kingdom",
        tier=3,
        website="https://www.muranolondon.com",
        cuisine_tags=["Italian", "Contemporary"],
        accolades=["2 Michelin Stars", "James Beard Award"],
        michelin_stars=2,
    ),
    Chef(
        id="chef_145",
        name="Shaun Rankin",
        restaurant="Ormer",
        location="Guernsey",
        country="United Kingdom",
        tier=3,
        website="https://www.ormerguernsey.com",
        cuisine_tags=["British", "Contemporary"],
        accolades=["1 Michelin Star"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_146",
        name="Bjorn van der Horst",
        restaurant="De Librije",
        location="Zutphen",
        country="Netherlands",
        tier=3,
        website="https://www.delibrijë.nl",
        cuisine_tags=["Dutch", "Contemporary"],
        accolades=["3 Michelin Stars"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_147",
        name="Jochen Weibel",
        restaurant="Über",
        location="Zurich",
        country="Switzerland",
        tier=3,
        website="https://www.uberresturant.ch",
        cuisine_tags=["Swiss", "Contemporary"],
        accolades=["2 Michelin Stars"],
        michelin_stars=2,
    ),
    Chef(
        id="chef_148",
        name="Frédéric Morel",
        restaurant="Restaurant Frederik",
        location="Copenhagen",
        country="Denmark",
        tier=3,
        website="https://www.restaurantfredrik.dk",
        cuisine_tags=["Nordic", "Contemporary"],
        accolades=["1 Michelin Star"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_149",
        name="Igor Guelmes",
        restaurant="A Través del Sabor",
        location="Buenos Aires",
        country="Argentina",
        tier=3,
        website="https://www.atravesdelsabor.com.ar",
        cuisine_tags=["Argentine", "Contemporary"],
        accolades=["1 Michelin Star"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_150",
        name="Mariano Martínez",
        restaurant="Ambrosía",
        location="Buenos Aires",
        country="Argentina",
        tier=3,
        website="https://www.ambrosia.com.ar",
        cuisine_tags=["Argentine", "Contemporary"],
        accolades=["1 Michelin Star"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_151",
        name="Constantino Armani",
        restaurant="Constant",
        location="São Paulo",
        country="Brazil",
        tier=3,
        website="https://www.constantinearmani.com.br",
        cuisine_tags=["Brazilian", "Contemporary"],
        accolades=["1 Michelin Star"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_152",
        name="Kimberly Escalante",
        restaurant="Escalante Culinary",
        location="Lima",
        country="Peru",
        tier=3,
        website="https://www.escalantculinary.pe",
        cuisine_tags=["Peruvian", "Contemporary"],
        accolades=["Regional Award"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_153",
        name="Leonor Espinoza",
        restaurant="Leo's Café",
        location="Mexico City",
        country="Mexico",
        tier=3,
        website="https://www.leoscafe.com.mx",
        cuisine_tags=["Mexican", "Contemporary"],
        accolades=["Regional Award"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_154",
        name="Rafael Olvera Martínez",
        restaurant="Lavanda",
        location="Mexico City",
        country="Mexico",
        tier=3,
        website="https://www.lavandamx.com",
        cuisine_tags=["Mexican", "Innovative"],
        accolades=["1 Michelin Star"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_155",
        name="Rodrigo Bellott",
        restaurant="Toro",
        location="Boston",
        country="United States",
        tier=3,
        website="https://www.toro boston.com",
        cuisine_tags=["Spanish", "Contemporary"],
        accolades=["James Beard Award"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_156",
        name="Stephanie Izard",
        restaurant="Little Goat",
        location="Chicago",
        country="United States",
        tier=3,
        website="https://www.littlegoatchicago.com",
        cuisine_tags=["American", "Contemporary"],
        accolades=["James Beard Award"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_157",
        name="José María Arzak",
        restaurant="Arzak",
        location="San Sebastián",
        country="Spain",
        tier=3,
        website="https://www.arzak.es",
        cuisine_tags=["Basque", "Innovative"],
        accolades=["3 Michelin Stars", "Lifetime Achievement"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_158",
        name="Andoni Aduriz Zabala",
        restaurant="Alinea",
        location="Chicago",
        country="United States",
        tier=3,
        website="https://www.alinea.com",
        cuisine_tags=["Molecular Gastronomy", "Innovative"],
        accolades=["3 Michelin Stars", "World's 50 Best"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_159",
        name="Aidan McGee",
        restaurant="McGee Culinary",
        location="Dublin",
        country="Ireland",
        tier=3,
        website="https://www.mccgeculinary.ie",
        cuisine_tags=["Irish", "Contemporary"],
        accolades=["Regional Award"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_160",
        name="Seamus Mullan",
        restaurant="Mullan's",
        location="Dublin",
        country="Ireland",
        tier=3,
        website="https://www.mullans.ie",
        cuisine_tags=["Irish", "Traditional"],
        accolades=["Regional Award"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_161",
        name="Magnus Nilsson",
        restaurant="Fäviken",
        location="Jämtland",
        country="Sweden",
        tier=3,
        website="https://www.faviken.se",
        cuisine_tags=["Nordic", "Innovative"],
        accolades=["2 Michelin Stars", "World's 50 Best"],
        michelin_stars=2,
    ),
    Chef(
        id="chef_162",
        name="Andreas Caminada",
        restaurant="Schloss Schauenstein",
        location="Graubünden",
        country="Switzerland",
        tier=3,
        website="https://www.schloss-schauenstein.ch",
        cuisine_tags=["Swiss", "Contemporary"],
        accolades=["3 Michelin Stars"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_163",
        name="Benoit Violier",
        restaurant="Restaurant de l'Hôtel de Ville",
        location="Crissier",
        country="Switzerland",
        tier=3,
        website="https://www.bertolio.ch",
        cuisine_tags=["French", "Classical"],
        accolades=["3 Michelin Stars"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_164",
        name="Patrick Henriroux",
        restaurant="Restaurant Patrick Henriroux",
        location="Courchevel",
        country="France",
        tier=3,
        website="https://www.patrick-henriroux.com",
        cuisine_tags=["French", "Contemporary"],
        accolades=["3 Michelin Stars"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_165",
        name="Christophe Bacquié",
        restaurant="Le Bacon",
        location="Antibes",
        country="France",
        tier=3,
        website="https://www.lebacon.com",
        cuisine_tags=["French", "Seafood"],
        accolades=["2 Michelin Stars"],
        michelin_stars=2,
    ),
    Chef(
        id="chef_166",
        name="Emmanuel Stroobants",
        restaurant="Stroob",
        location="Ostend",
        country="Belgium",
        tier=3,
        website="https://www.stroob.be",
        cuisine_tags=["Belgian", "Contemporary"],
        accolades=["2 Michelin Stars"],
        michelin_stars=2,
    ),
    Chef(
        id="chef_167",
        name="Sven Elverfeld",
        restaurant="Aqua",
        location="Dusseldorf",
        country="Germany",
        tier=3,
        website="https://www.aqua-dusseldorf.de",
        cuisine_tags=["German", "Contemporary"],
        accolades=["3 Michelin Stars"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_168",
        name="J. Boon",
        restaurant="Boon",
        location="Amsterdam",
        country="Netherlands",
        tier=3,
        website="https://www.boon-amsterdam.nl",
        cuisine_tags=["Dutch", "Contemporary"],
        accolades=["1 Michelin Star"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_169",
        name="Peter Cluskey",
        restaurant="Cluskey's",
        location="Antrim",
        country="Northern Ireland",
        tier=3,
        website="https://www.cluskeys.com",
        cuisine_tags=["Irish", "Traditional"],
        accolades=["Regional Award"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_170",
        name="Robby Melloul",
        restaurant="Melloul Culinary",
        location="Jerusalem",
        country="Israel",
        tier=3,
        website="https://www.melloilculinary.co.il",
        cuisine_tags=["Israeli", "Mediterranean"],
        accolades=["Regional Award"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_171",
        name="Assaf Granit",
        restaurant="Granit",
        location="Tel Aviv",
        country="Israel",
        tier=3,
        website="https://www.granitrestaurant.co.il",
        cuisine_tags=["Israeli", "Contemporary"],
        accolades=["1 Michelin Star"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_172",
        name="Ali Sazegar",
        restaurant="Sazegar",
        location="Tehran",
        country="Iran",
        tier=3,
        website="https://www.sazegar.ir",
        cuisine_tags=["Persian", "Contemporary"],
        accolades=["Regional Award"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_173",
        name="Hou Ying",
        restaurant="Dragon Palace",
        location="Shanghai",
        country="China",
        tier=3,
        website="https://www.dragonpalace.com.cn",
        cuisine_tags=["Chinese", "Regional"],
        accolades=["Regional Award"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_174",
        name="Chen Ying",
        restaurant="Chen's",
        location="Beijing",
        country="China",
        tier=3,
        website="https://www.chensrestaurant.cn",
        cuisine_tags=["Chinese", "Traditional"],
        accolades=["Regional Award"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_175",
        name="Thongchai Samraidee",
        restaurant="Samraidee",
        location="Bangkok",
        country="Thailand",
        tier=3,
        website="https://www.samraidee.co.th",
        cuisine_tags=["Thai", "Contemporary"],
        accolades=["1 Michelin Star"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_176",
        name="Somchai Ketkaew",
        restaurant="Somchai's",
        location="Bangkok",
        country="Thailand",
        tier=3,
        website="https://www.somchais.co.th",
        cuisine_tags=["Thai", "Traditional"],
        accolades=["Regional Award"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_177",
        name="Bui Vu Tung",
        restaurant="Bui's",
        location="Ho Chi Minh City",
        country="Vietnam",
        tier=3,
        website="https://www.buis-hcm.vn",
        cuisine_tags=["Vietnamese", "Traditional"],
        accolades=["Regional Award"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_178",
        name="Pham Tuan Vu",
        restaurant="Tuanvu",
        location="Hanoi",
        country="Vietnam",
        tier=3,
        website="https://www.tuanvu.vn",
        cuisine_tags=["Vietnamese", "Contemporary"],
        accolades=["Regional Award"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_179",
        name="Gunawan Ismail",
        restaurant="Locavore",
        location="Jakarta",
        country="Indonesia",
        tier=3,
        website="https://www.locavore-jakarta.com",
        cuisine_tags=["Indonesian", "Contemporary"],
        accolades=["1 Michelin Star", "World's 50 Best"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_180",
        name="Juna Jiang",
        restaurant="Jiang Cuisine",
        location="Singapore",
        country="Singapore",
        tier=3,
        website="https://www.jiangcuisine.sg",
        cuisine_tags=["Asian Fusion", "Contemporary"],
        accolades=["Regional Award"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_181",
        name="Vikram Saran",
        restaurant="Saran",
        location="New Delhi",
        country="India",
        tier=3,
        website="https://www.saranrestaurant.co.in",
        cuisine_tags=["Indian", "Contemporary"],
        accolades=["1 Michelin Star"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_182",
        name="Manish Mehrotra",
        restaurant="Indian Accent",
        location="New Delhi",
        country="India",
        tier=3,
        website="https://www.indianaccent.com",
        cuisine_tags=["Indian", "Contemporary"],
        accolades=["1 Michelin Star", "World's 50 Best"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_183",
        name="Kylie Kwong",
        restaurant="Kylie",
        location="Sydney",
        country="Australia",
        tier=3,
        website="https://www.kylie-kwong.com",
        cuisine_tags=["Australian", "Indigenous"],
        accolades=["1 Michelin Star"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_184",
        name="Mark Best",
        restaurant="Sepia",
        location="Sydney",
        country="Australia",
        tier=3,
        website="https://www.sepiasydney.com",
        cuisine_tags=["Australian", "Contemporary"],
        accolades=["2 Michelin Stars"],
        michelin_stars=2,
    ),
    Chef(
        id="chef_185",
        name="Attica",
        restaurant="Attica",
        location="Melbourne",
        country="Australia",
        tier=3,
        website="https://www.attica.com.au",
        cuisine_tags=["Australian", "Contemporary"],
        accolades=["2 Michelin Stars", "World's 50 Best"],
        michelin_stars=2,
    ),
    Chef(
        id="chef_186",
        name="Mark McEwan",
        restaurant="Bymark",
        location="Toronto",
        country="Canada",
        tier=3,
        website="https://www.bymark.ca",
        cuisine_tags=["Canadian", "Contemporary"],
        accolades=["1 Michelin Star"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_187",
        name="Vikram Mital",
        restaurant="Mital",
        location="Vancouver",
        country="Canada",
        tier=3,
        website="https://www.mital.ca",
        cuisine_tags=["Indian Fusion", "Contemporary"],
        accolades=["Regional Award"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_188",
        name="Roberto Pettirossi",
        restaurant="Petto",
        location="Santiago",
        country="Chile",
        tier=3,
        website="https://www.petto-restaurant.cl",
        cuisine_tags=["Chilean", "Contemporary"],
        accolades=["1 Michelin Star"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_189",
        name="Carolina Flores",
        restaurant="Carolina's",
        location="Rio de Janeiro",
        country="Brazil",
        tier=3,
        website="https://www.carolinaflores.com.br",
        cuisine_tags=["Brazilian", "Contemporary"],
        accolades=["Regional Award"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_190",
        name="Carlos Minakata",
        restaurant="Minakata",
        location="Cusco",
        country="Peru",
        tier=3,
        website="https://www.minakata.pe",
        cuisine_tags=["Peruvian", "Traditional"],
        accolades=["Regional Award"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_191",
        name="Lilia Zetina",
        restaurant="Zetina",
        location="Oaxaca",
        country="Mexico",
        tier=3,
        website="https://www.zetina.com.mx",
        cuisine_tags=["Mexican", "Regional"],
        accolades=["Regional Award"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_192",
        name="Edgar Núñez",
        restaurant="Núñez",
        location="Guatemala City",
        country="Guatemala",
        tier=3,
        website="https://www.nunez.gt",
        cuisine_tags=["Guatemalan", "Contemporary"],
        accolades=["Regional Award"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_193",
        name="Ronald Gutiérrez",
        restaurant="Gutiérrez",
        location="Havana",
        country="Cuba",
        tier=3,
        website="https://www.gutierrez.cu",
        cuisine_tags=["Cuban", "Traditional"],
        accolades=["Regional Award"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_194",
        name="Oscar San Juan",
        restaurant="San Juan",
        location="San Juan",
        country="Puerto Rico",
        tier=3,
        website="https://www.sanjuanpr.com",
        cuisine_tags=["Puerto Rican", "Contemporary"],
        accolades=["Regional Award"],
        michelin_stars=0,
    ),
    Chef(
        id="chef_195",
        name="Jean-Paul Jeunet",
        restaurant="Jeunet",
        location="Lyon",
        country="France",
        tier=3,
        website="https://www.jeunet.fr",
        cuisine_tags=["French", "Contemporary"],
        accolades=["1 Michelin Star"],
        michelin_stars=1,
    ),
    Chef(
        id="chef_196",
        name="Christophe Moret",
        restaurant="Moret",
        location="Fontainebleau",
        country="France",
        tier=3,
        website="https://www.moret-restaurant.fr",
        cuisine_tags=["French", "Contemporary"],
        accolades=["3 Michelin Stars"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_197",
        name="Bernard Loiseau",
        restaurant="Loiseau",
        location="Saulieu",
        country="France",
        tier=3,
        website="https://www.bernard-loiseau.com",
        cuisine_tags=["French", "Light Cuisine"],
        accolades=["3 Michelin Stars"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_198",
        name="Michel Bras",
        restaurant="Bras",
        location="Laguiole",
        country="France",
        tier=3,
        website="https://www.michel-bras.fr",
        cuisine_tags=["French", "Innovative"],
        accolades=["3 Michelin Stars"],
        michelin_stars=3,
    ),
    Chef(
        id="chef_199",
        name="Stéphane Fretz",
        restaurant="Fretz",
        location="Strasbourg",
        country="France",
        tier=3,
        website="https://www.fretz.fr",
        cuisine_tags=["French", "Contemporary"],
        accolades=["2 Michelin Stars"],
        michelin_stars=2,
    ),
    Chef(
        id="chef_200",
        name="Nicolas Isnard",
        restaurant="Isnard",
        location="Provence",
        country="France",
        tier=3,
        website="https://www.isnard-provence.fr",
        cuisine_tags=["French", "Provençal"],
        accolades=["1 Michelin Star"],
        michelin_stars=1,
    ),
]

# Combined list of all chefs
ALL_CHEFS = TIER_1_CHEFS + TIER_2_CHEFS + TIER_3_CHEFS


def get_chefs_by_tier(tier: int) -> list[Chef]:
    """Get chefs by priority tier.

    Args:
        tier: Tier number (1, 2, or 3).

    Returns:
        List of chefs for that tier.
    """
    if tier == 1:
        return TIER_1_CHEFS
    elif tier == 2:
        return TIER_2_CHEFS
    elif tier == 3:
        return TIER_3_CHEFS
    return []


def get_chef_by_id(chef_id: str) -> Optional[Chef]:
    """Get a chef by ID.

    Args:
        chef_id: Chef ID.

    Returns:
        Chef object or None.
    """
    for chef in ALL_CHEFS:
        if chef.id == chef_id:
            return chef
    return None


def get_all_chefs() -> list[Chef]:
    """Get all 200 chefs.

    Returns:
        List of all Chef objects.
    """
    return ALL_CHEFS
